project:
  type: book

book:
  title: "Quantum Mechanics"
  author: "Andrew Binder, Eric Du"
  date: "8/13/2025"

  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

  page-footer: "[Home](../landing/index.qmd)"


bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
      - styles.scss
  pdf:
    documentclass: scrreprt
    include-in-header: boxed-theorems.tex



