project:
  type: book

book:
  title: "Quantum Mechanics"
  author: "Andrew Binder, Eric Du"
  date: "8/13/2025"

  chapters:
    - index.qmd
    - part: part1/part1.qmd
      chapters: 
        - part1/intro.qmd
        - part1/summary.qmd
    - references.qmd

  page-footer: "[Home](../)"


bibliography: references.bib

format:
  html:
    html-math-method: mathjax
    theme:
      - cosmo
      - brand
      - styles.scss
    include-after-body:
      - theorem-collapse.html
    math:
      macros:
        "\\RR": "\\mathbb{R}"

  pdf:
    documentclass: scrreprt
    include-in-header: 
      - boxed-theorems.tex
      - macros.tex


editor:
  render-on-save: true
