project:
  type: book

book:
  title: "Quantum Mechanics"
  author: 
  - name: Eric Du
    email: eric.du03@berkeley.edu
    affiliation: UC Berkeley
  - name: Andrew Binder
    email: abinder@berkeley.edu
    affiliation: UC Berkeley, Stony Brook University

  chapters:
    - index.qmd
    - part: part1/part1.qmd
      chapters: 
        - part1/origins.qmd
        - part1/formalism.qmd
    - references.qmd

  page-footer: "[Home](../)"


bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
      - styles.scss
    include-after-body:
      - theorem-collapse.html
    html-math-method: mathjax
    include-in-header:
      - text: |
          <script>
          window.MathJax = {
            loader: { load:['[tex]/physics']},
            tex:    { packages: {'[+]': ['physics'] } }
          };
          </script>
          <link rel="stylesheet" href="https://tikzjax.com/v1/fonts.css">
          <script src="https://tikzjax.com/v1/tikzjax.js"></script>


  pdf:
    documentclass: scrreprt
    include-in-header: 
      - boxed-theorems.tex
      - macros.tex


editor:
  render-on-save: true
