project:
  type: book

book:
  title: "Quantum Mechanics"
  author: 
  - name: Eric Du
    email: eric.du03@berkeley.edu
    affiliation: UC Berkeley
  - name: Andrew Binder
    email: abinder@berkeley.edu
    affiliation: UC Berkeley, Stony Brook University

  chapters:
    - index.qmd
    - part: part1/part1.qmd
      chapters: 
        - part1/origins.qmd
        - part1/formalism.qmd
    - references.qmd

  page-footer: "[Home](../)"


bibliography: references.bib

format:
  html:
    html-math-method: mathjax
    theme:
      - cosmo
      - brand
      - styles.scss
    include-after-body:
      - theorem-collapse.html
    math:
      macros:
        "\\RR": "\\mathbb{R}"

  pdf:
    documentclass: scrreprt
    include-in-header: 
      - boxed-theorems.tex
      - macros.tex


editor:
  render-on-save: true
