# Preface {.unnumbered}
Welcome to our Quantum Mechanics book!

## What is This?
This book contains a comprehensive catalog of the fundamentals of quantum mechanics (QM), to the extent that
the authors have encountered the topics and the material. With this book, our objective is to provide an
intuitive approach to learning quantum mechanics, and share with you the tips and tricks we learned while we
were studying the field. Whether you're just getting started with QM or are already familiar with some of the
content covered, we hope there is something here for you to learn!

### Fundamental Structure
We have divided this book into three major parts, in an attempt to effectively compartmentalize the vast
amount of material we aim to cover. The first part covers fundamental theory; specifically, it details the
basic building blocks of quantum mechanics and helps us transition from the classical frame to the quantum
one. The second part shifts focus to approximation methods. As we will learn, solving quantum systems exactly
is nigh-impossible, which necessitates the need to approximate in order to effectively study physical
systems. The final part will explore some more advanced special topics and extend beyond quantum mechanics
into the relativistic frame. 

## Some Notational Logistics
Before we get started with the content, let's go over some basic elements you will see throughout this book.

:::{.definition #def-sample}
# A Thing
Whenever we come across a new term, we will define it like so.
:::

:::{.notation}
We will also occasionally highlight specific mathematical notation like so.
:::

:::{.lemma #lem-sample}
# Auxiliary Trick
If there's a relevant fact that services a larger result, we will encode it as a lemma.
:::

:::{.theorem #thm-sample}
# Major Result
When we arrive at a major result, we will encode it as a theorem.
:::
:::{.proof}
We will take care to prove theorems as soon as possible.
:::

:::{.corollary #cor-sample}
# Consequence
If a theorem has an important consequence, we'll label it as a corollary.
:::

:::{.remark}
If there's an important side note we wish to highlight, we'll place those here.
:::

:::{.example #exm-sample}
# What Just Happened
Examples will help us illustrate what just happened.
:::

:::{.warning}
Read these! These contain common mistakes and things to be careful.
:::

We will try to keep such remarks and warnings to a minimum. We will also try our best to keep theorems and 
important results cross-referenceable; for instance, clicking @thm-sample will take you to the corresponding 
theorem (or hovering over it will give you a summary). Finally, this book combines elements from various 
books that we've encountered over our own journey through quantum mechanics, a full list of which can be 
found in the [references](references.qmd) page.

One last thing: there is a lot of content in this book, and there are only two of us actively maintaining it. 
If you find that there are any errors, or you wish to make any suggestions, please reach out via email and let 
us know! We both want this book to be as approachable as it can be, and are always looking for ways to improve 
it. You can find our emails in the author list at the top of the page. 
 
 Happy reading!
