# 1D Wave Mechanics {#sec-1d-wave-mechanics} 
<!-- TODO: The first section will need to be updated once I write up the "quantum from classical" chapter -->
Having laid the foundation with formalism, connected said formalism to experimental results through
postulates, used these postulates to derive quantum analogs to some classical quantities, and derived the
Schrödinger equation (which will be the fundamental equation we aim to solve), we are now
ready to tackle some basic problems and learn how to solve certain quantum mechanical systems. In this chapter, we will utilize the time-independent Schrödinger equation to extract the allowed states in our system, and explore some
canonical problems studied in most quantum mechanics books. Finally, we will look at how to incorporate time
dependence and transform a time-independent solution $\psi(x)$ into a time-dependent $\Psi(x, t)$. 

<!-- I have removed this because I feel it is now redundant
## The Wavefunction
As mentioned in [REF formalisms], the fundamental object in our study of quantum mechanics is the
**wavefunction**, denoted $\psi(x, t)$ or $\Psi(x, t)$, which is a vector in our Hilbert space $\mathcal{E}$. 
This is also sometimes denoted as the **state** of our system, and is represented in bra-ket
notation by $\ket{\psi}$. To begin our discussion, we will focus on 1D wave functions; that is, wavefunctions
of the form $\psi(x, t)$ (so only having one position coordinate), and then later generalize this notion 
to multiple dimensions. This is summarized in the box below:

:::{.notation}
The state of a quantum system is denoted by its wavefunction $\psi$, which lives in a Hilbert space
$\mathcal{E}$, and is represented in functional form by $\psi(x)$ or in its vector form by $\ket{\psi}$. 
:::

Recall that $\psi$ itself isn't something that can be directly observed, but it contains all the information
about the quantum system. What we do observe is $|\psi|^2$, which represents the probability density of
measuring a particular observable (assuming of course, that $\psi$ is expressed in the basis of the
corresponding observable). As $|\psi|^2$ is a probability density, it must follow the law of total
probability, which is written as:
$$
	\int_{-\infty}^{\infty} |\psi(x, t)|^2 \ dx = \int_{-\infty}^{\infty} \psi(x) \psi^{*}(x) \ dx = 1 
$$
at all $t$, with the $\psi^{*}$ being the complex conjugate of $\psi$. Intuitively, this should also make sense: 
this is essentially saying that the probability you measure *some* value of your observable is guaranteed. 

:::{.warning}
Note that this does NOT imply that $\psi$ is necessarily integrable, and that's perfectly fine! Remember that
what we physically observe is the probability $|\psi|^2$ and not $\psi$, so there is no requirement on what
$\psi$ needs to be. Formally, $\psi$ belongs to a class of functions which are considered
*square-integrable*, namely the property that $|\psi|^2$ must be integrable.  
:::
-->

## Time-Independent Schrödinger Equation
<!-- I have commented this section out while I draft up the quantum from classical chapter; once it exists,
let's revisit this and write whatever content you deem relevant -->
<!--
Now, we will take a look at how we actually write down the wavefunction $\psi$. To begin, recall that from
[REF formalisms] that $\psi$ can be expressed in many different ways, depending on the basis we choose.
One particular basis of interest to us is the *energy* basis, which are eigenstates of the Hamiltonian
operator $\hat{H}$. These are of particular interest to us since at a high level, one primary property we
care about in our quantum system is the energy of our particles. Now, since $\psi$ is written as a linear 
combination of these eigenstates, the next logical step is to solve the eigenvalue equation for $H$ to find them. 
This equation is known as the **time-independent Schrodinger equation (TISE)**, which we
introduce below: 

:::{.theorem #thm-tise}
# Time-Independent Schrödinger Equation
Given a Hamiltonian $\hat{H}$, its energy eigenstates are given by the eigenvalue equation:
$$
	\hat{H} \ket{\psi} = E \ket{\psi}
$$
:::
This equation is at the heart of quantum mechanics -- everything we do from here on out is all in the name of
solving this equation. Don't let its simplicity fool you, though: this equation is deceptively complex. 

In light of this, there are still some things we can do. To begin, we should unpack the Hamiltonian 
operator $\hat{H}$, and write it down in a "nicer" form. First, we go back to the classical (non-quantum) definition
of the Hamiltonian as the sum of kinetic and potential energies of a system: 
<!-- perhaps we should include a citation to the classical mechanics part of the book, when possible -->   
<!--$$
	H = T + V
$$
The kinetic energy, written in terms of the momentum $p$, is: 
$$
	T = \frac{p^2}{2m}
$$
So the Hamiltonian can be written as:
$$
	H = \frac{p^2}{2m} + V(x)
$$
For now (and for most of this book), we will consider time-independent potentials $V(x)$, meaning the energy
will depend exclusively on the position in space and will not evolve in time.

An additional simplification we will make in this chapter is considering systems in <u>one dimension</u>.
This reduces the degrees of freedom and simplifies our equation dramatically.

:::{.remark}
The abstraction to three dimensions will not be as complicated as it may seem at first, but for the sake of
clarity, we will limit our discussion to one-dimensional systems, for now.
:::

To transform this Hamiltonian into the quantum language, we promote all observables to operators (motivated by our
postulate), so this means we promote $p$ to $\hat{p}$, and $x$ to $\hat{x}$. In one dimension, these
operators have the following form:
$$\hat{x} = x, \quad \hat{p} = -i\hbar\pdv{x}$$
So, the time-independent Schrödinger equation now reads:
$$
	\left(-\frac{\hbar^2}{2m} \pdv[2]{x} + V(x)\right) \ket{\psi} = E \ket{\psi}
$$
Now, the path forward is clear: for different systems, we substitute in the appropriate potential $V(x)$,
and solve the differential equation for $\psi$, and out come the energy eigenstates! 
-->
:::{.notation}
Since we are only dealing in one dimension and have abstracted out time dependence, our function is
technically single-variable, meaning the derivative is a regular total derivative. However, since this will
not generally be the case, we will use the partial derivative notation to maintain consistency. In the
following problems, though, treat this derivative as $-i\hbar\dv{x}$. 
:::

## Fundamental Problems
As we saw above, the main quantity that will determine the behavior of the system (and the resulting energy
eigenstates/eigenvalues) will be the potential $V$, since the kinetic energy will always be represented by
the same quantity/operator. Thus, the systems we address will each differ only in the potential term.

Life is unfortunately unfair, meaning most of the potentials relevant to describing real-world phenomena will
yield equations that are very difficult, if not completely impossible, to solve analytically and exactly.
Fortunately for us, however, there are a few fundamental examples that *are* analytically solvable, and they
will greatly aid us in getting acquainted with the Schrödinger equation, how to utilize it, and what certain
energies can tell us about the form of the resulting wavefunction.

:::{.warning}
It should be noted that pretty much all of the potentials we will examine in this section are enitrely
nonphysical! This is not of concern to us at this stage, though; despite being nonphysical and not actually
appearing in the real world, these potentials will give us practice with solving for energy eigenstates with
the Schrödinger equation and will serve as toy models to build approximations to more realistic potentials as
we try to tackle more advanced systems.
:::

### The Free Particle {#sec-free-particle}
What's the simplest form of $V(x)$? Well, $V(x) = 0$ of course! This case is known as the *free particle*, as
it's free from any other influence. Here, the time-independent Schrödinger equation reads:    
$$
	-\frac{i\hbar}{2m} \dv[2]{\psi}{x} = E \psi(x)
$$
This is a simple second-order ODE[^ode], whose solutions are complex exponentials. To solve this, let's
absorb all constants into a term which we'll call $k$:
$$
	k = \frac{\sqrt{2mE}}{\hbar}
$$
Our ODE now reads:
$$
	\frac{\partial^2}{\partial x^2} \psi = -k^2 \psi
$$
This has a well-known solution given as a sum of complex exponentials:
$$
	\psi(x) = Ae^{ikx} + Be^{-ikx}
$$
The constants $A$ and $B$ will relate to the constants absorbed into $k$.

:::{.remark}
Intuitively, this makes sense: these are just *plane waves* travelling through space unimpeded, which is expected when we have no potential $V$. In particular, this solution is a superposition of a wave travelling to the
right with positive $k$ and one to the left with negative $k$.
:::

However, this solution has a problem: **it isn't normalizabile**! If we try to check the normalization:
$$\begin{align*}
	\int_{-\infty}^{\infty}\left|Ae^{ikx}+Be^{-ikx}\right|^2dx &= \int_{-\infty}^{\infty}\left( Ae^{ikx} + Be^{-ikx} \right)\left(
	A^{*}e^{-ikx} + B^{*}e^{ikx}\right)dx = \\
  &= \int_{-\infty}^{\infty} |A|^2 + |B|^2 + AB^{*}e^{2ikx} + A^{*}Be^{-2ikx} \ dx = \infty
\end{align*}$$
Our integral diverges regardless of the choice of $A$ and $B$, meaning it's not normalizable. So what does this mean? Well, the only natural conclusion is that such a
wavefunction is inadmissible, and therefore <u>a free particle with a definite energy $E$ cannot exist</u>. Instead,
the solution is to consider a linear combination of a *range* of energies, represented as an integral:
$$
	\psi(x) = \frac{1}{\sqrt{2\pi}} \int_{-\infty}^{\infty}\phi(k) e^{ikx} \ dk
$${#eq-free-particle}
Here, $\phi(k)$ essentially represents the "weight" (or contribution) that the wave with momentum $k$
conributes to the overall $\psi(x)$. Those that are familiar with Fourier analysis will recognize this equation 
immediately, and point out that $\psi(x)$ and $\phi(k)$ are related by the Fourier transform:
$$
	\phi(k) = \frac{1}{\sqrt{2\pi}} \int_{-\infty}^{\infty}\psi(x) e^{-ikx} \ dx
$$

:::{.remark}
This relation means that $\psi(x)$ and $\phi(k)$ are actully equivalent descriptions of the
same state that live in different spaces! $\psi(x)$ lives in "configuration space" while $\phi(k)$ lives in
"$k$-space".
:::

This doesn't resolve our initial problem though: how do we find $\phi(k)$? The trick lies in the fact that
$\phi(k)$ has no explicit time dependence, so we can pick a time for which we know the form of the (normalized) $\psi(x)$ and solve for $\phi(k)$ there. Generally, the time is chosen as $t = 0$:
$$
	\phi(k) = \frac{1}{\sqrt{2\pi}} \int_{-\infty}^{\infty} \psi(x, 0) e^{-ikx} \ dx
$$
This can then be plugged into @eq-free-particle to get $\psi(x)$. In essence, because the Fourier transform
doesn't touch the normalization condition at all (it just provides a means to transform from position to
frequency space), once you start with a normalized wavefunction, it will always be normalized.   

### The Infinite Square Well
With $V(x) = 0$ solved, let's move forward and look at our first non-trivial $V(x)$, defined by the piecewise
function:
$$
	V(x) = 
	\begin{cases}
	0 & 0 \leq x \leq a\\
	\infty & \text{otherwise}
	\end{cases}
$$
This is called the *infinite square well*, appropriately named since the graphical representation of the
potential is a well whose walls are infinitely tall:   

:::{#fig-infinite-square-well fig-env="figure*" fig-pos="h"}
```{.tikz}
	\begin{tikzpicture}[scale=1.5]
		\draw[thick, stealth-stealth] (-1, 3) node[left] {$\infty$} -- (-1, 0) node[left] {$0$} 
		-- (1, 0) node[right] {$a$} -- (1, 3) node[right] {$V(x)$};
	\end{tikzpicture}
```
The infinite square well; the width is $a$, and both walls extend infinitely upward.
:::

To solve this differential equation, we will consider $V(x)$ in the interval $[0, a]$ separately from
everywhere else, then tie the solutions together. Luckily for us, both solutions are relatively simple.

Between since $V(x) = 0$ inside the well, our problem reverts to the aforementioned free particle, where our
solutions are just travelling plane waves. For reasons that will be apparent later, we will choose the
trigonometric representation of a travelling wave:
$$
	\psi(x) = A \sin(kx) + B \cos(kx)
$$
This is an equivalent way to representing a travelling wave, and the conversion is given to us by Euler's
formula:
$$
	e^{ikx} = \cos(kx) + i \sin(kx)
$$
Now, outside of $[0, a]$, the potential is infinite, so the only sensible solution is $\psi = 0$ (the
wavefunction vanishes). 

Okay, so we have the solutions in these separate regimes, how do we tie them together? The key is to realize
that $\psi(x)$ must be *continuous*, since $x$ (the position) is a continuous variable and $|\psi(x)|^2$ must
represent the probability density in position. So, since the wavefunction is identically zero outside the
well, it must approach zero from inside the well at the boundaries:  
$$
	\lim_{x \to 0} \psi(x) = \lim_{x \to a} \psi(x) = 0
$$
First, we handle the easier $x = 0$ case:
$$
	\psi(0) = A \sin(0) + B \cos(0) \implies B = 0
$$
Now for the $x = a$ case:
$$
	0 = \psi(a) = A \sin(ka)
$$
Since $A$ can't be $0$ (that would give us a nonexistent wavefunction), $ka$ must be an integer multiple of $\pi$ for the sine term to vanish. Hence, $ka = n\pi$, which we can generalize by subscripting $k$ to correspond to the $n$th solution:
$$k_n = \frac{n\pi}{a}$$
Here we see a very intriguing property fall out of the mathematics: the simple restriction of our wavefunction in space *forces* our wavefunction to
belong to a discrete family of functions, parametrized by the integer $n$. As a consequence, this also
quantizes the allowable energies:  
$$
	E_n = \frac{p^2}{2m} = \frac{\hbar^2 k_n^2}{2m}
$$
This is the first result that fundamentally differs from classical notions of thinking, as energy is always
thought to be a continuum in classical physics. Finally, all we have to do now is to find the normalization
constant $A$, which we do by enforcing our total probability condition:
$$
	\int_{-\infty}^{\infty} |A|^2 \sin^2 kx \ dx =  |A|^2 \frac{a}{2} \implies |A| = \sqrt{\frac{2}{a}}
$$
Therefore, the full solution to the infinite square well is the following discrete set of wavefunctions $\psi_n$:
$$
	\boxed{\psi_n(x) = \sqrt{\frac{2}{a}} \sin\left( \frac{n\pi}{a}x \right)}
$${#eq-isw-wavefunctions}
These incidentally correspond to standing modes in a cavity, visualized below.

:::{#fig-isw-solutions fig-env="figure*" fig-pos="h"}
```{.tikz}
	\begin{tikzpicture}[scale=1.5]
		\draw[thick, stealth-stealth] (-1, 3) node[left] {$\infty$} -- (-1, 0) node[left] {$0$} 
		-- (1, 0) node[right] {$a$} -- (1, 3) node[right] {$V(x)$};
    \draw[very thick,blue!40!cyan!80] (-1,0) sin (0,1) node[above] {$n=1$} cos (1,0);
    \draw[very thick,red!70!white] (-1,0) sin (-0.5,1) cos (0,0) sin (0.5,-1) node[below] {$n=2$} cos (1,0);
    \draw[very thick,yellow!40!orange] (-1,0) sin (-0.666,1) cos (-0.333,0) sin (0,-1) node[left,xshift=-0.25cm] {$n=3$} cos (0.333,0) sin (0.666,1)
cos (1,0);
	\end{tikzpicture}
```
A few infinite square well wavefunction solutions visualized.
:::

Hopefully, this example helps visualize how the idea of quantization falls out very naturally
from the simple restriction that $\psi$ must be continuous: it's an example of how quantum mechanics is
fundamentally different from classical mechanics, and yet it makes extremely accurate descriptions of the
phenomena around us.

### Delta Function Potentials
In this section, we will consider $V(x)$ of a very particular form:
$$
	V(x) = -a\delta(x)
$$
Here, $\delta(x)$ refers to the *Dirac delta function*:

:::{.definition #def-dirac-delta}
# Dirac Delta Function 
The *Dirac delta function*, denoted $\delta(x-x_0)$, is defined as the following:
$$\delta(x-x_0) = \begin{cases}\infty&x=x_0\\0&\text{otherwise}\end{cases}$$
Crucially, it is also defined to have a bounded integral:
$$\int_{-\infty}^{\infty}\delta(x-x_0)dx = 1$$
This can be thought of as the continuous version of the Kronecker delta.
:::

This is quite a peculiar object. It's not a "function" in the traditional sense, and instead 
defined as a function whose value is zero nearly everywhere but integrates to 1 over the entire real 
line. There is no true function that simultaneously satisfies these properties, hence the delta function isn't
really considered a "function".[^delta-function] However, it often makes an appearance in theoretical and experimental
physics since many phenomena around us can be modeled approximately as delta functions. 


:::{#fig-delta-well fig-env="figure*" fig-pos="h"}
```tikz
\begin{tikzpicture}
  \draw[thick] (-2,0) node[left] {$0$} -- (-0.25,0) cos (-0.125,-1.5) sin (0,-3) node[below] {$-\infty$} cos (0.125,-1.5) sin (0.25,0) -- (2,0) node[right] {$V(x)$};
\end{tikzpicture}
```
The delta function well potential. The width and the depth are exaggerated to make it look more reminiscent of an actual well; in reality, it is infinitesimally thin and infinitely deep.
:::

Just like all of the potentials we've seen so far, let's throw this $V(x)$ into the differential equation:
$$
	-\frac{\hbar^2}{2m} \pdv[2]{\psi}{x} - a \delta(x) \psi = E \psi 
$$
Now, let's consider two separate cases: when $x < 0$ and $x > 0$. In both these cases, $\delta(x) = 0$, so
therefore our differential equation reduces to:
$$
	-\frac{\hbar^2}{2m} \pdv[2]{\psi}{x} = E \psi \implies \pdv[2]{\psi}{x} = -\frac{2mE}{\hbar^2} \psi
$$
Now it's time to mention a detail we haven't really talked about until now: what is the sign of $E$ that
we're dealing with? Whether $E$ is positive or negative will determine the sign of the prefactor, which in
turn impacts what kind of solutions the differential equation will yield. In
particular, when $E > 0$, then we admit *scattering* solutions, and when $E < 0$ we admit *decaying*
solutions.[^scatter-decay]

The decaying solutions are slightly easier to deal with, so let's tackle those first. In this case, $E < 0$
so the prefactor on $\psi$ is positive, hence we can write:
$$
	\pdv[2]{\psi}{x} = -\frac{2mE}{\hbar^2} = \kappa^2 \psi
$$
Here, just like with the infinite square well, we have absorbed all constants into a constant which we'll
call $\kappa$:
$$
	\kappa = \frac{\sqrt{-2mE}}{\hbar}
$${#eq-3-energy}
Remember, $\kappa$ is still positive here since $E$ is negative. Just like the free particle case, a
linear combination of positive and negative exponentials constitutes a valid solution:
$$
	\psi = Ae^{\kappa x} + Be^{-\kappa x}
$$
At this point, we acknowledge physical boundary conditions. First, let's consider the $x < 0$ case.
Here, we require that $\psi$ doesn't blow up as $x \to -\infty$, which is only possible if the negative
exponential vanishes. Likewise, when $x > 0$ we don't want $\psi$ to blow up as $x \to \infty$, hence the 
positive exponential term vanishes. Put put together, we have the following "pieces" of our wavefunction:
$$
	\psi_L = Ae^{\kappa x} \quad \psi_R = Be^{-\kappa x}
$$
Now, we need to join the two together to get one complete wavefunction. To do this, we enforce our notion of
continuity, which is to say that $\psi_L$ and $\psi_R$ must attain the same value at $x = 0$. This is easy;
since they both have the same exponential, this is just telling us that $A = B$. So, the wavefunction looks
like:
$$
	\psi = \begin{cases}
	A e^{\kappa x} & x < 0\\
	A e^{-\kappa x} & x > 0\\
	\end{cases}
$$
To find $A$, we enforce normalization. To do this, notice that $\psi$ is symmetric about $x = 0$, so we can
write the integral as: 
$$
	1 = \int_{-\infty}^{\infty}|\psi|^2 \ d x = 2 \int_{0}^{\infty} |A|^2 e^{-2\kappa x} \ d x =
	\frac{|A|^2}{\kappa} 
$$
So the solution is $|A|^2 = \kappa$, or $A = \sqrt{\kappa}$, and our wavefunction is then:
$$
	\psi = \sqrt{\kappa} e^{-\kappa |x|}
$$
Notice how we combined the piecewise expression into a single one with the absolute value in the exponential. 
But what would be the energy of such a wavefunction? To find it, we have to look more closely at the behavior
of $\psi$ around $x = 0$. To find the energy, we need to impose an additional condition that we haven't
encountered yet: continuity of $\psi'$ (the wavefunction's derivative). 

First off, we should try and understand the reason why continuity in $\psi'$ is needed, of which there are two. 
The first comes directly from our time-independent Schrodinger equation. Recall that the equation reads:
$$
	\left(-\frac{i\hbar}{2m} \pdv[2]{x} + V(x)\right) \ket{\psi} = E \ket{\psi}
$$
isolating the term on the left, we have:
$$
	-\frac{i\hbar}{2m} \pdv[2]{\psi}{x} = (E - V(x)) \psi
$$
since $\psi$ is continuous then the right side is continuous, 
which means the left must be also. If $\psi''$ is continuous, then this implies that 
$\psi'$ must be differentiable, hence it must be continuous. 

But what if $V(x)$ is not continuous? We've seen two examples already where $V(x)$ is not continuous, so what
then? As it turns out, even when $V(x)$ is discontinuous, as long as $V(x)$ is not *infinite*, then
continuity in $\psi'$ is still guaranteed:

:::{.theorem #thm-continuity}
# Continuity of Wavefunction and its Derivative
For a given potential $V(x)$, as long as $V(x)$ is finite, the wavefunction $\psi$ and its derivative
$\psi'$ is always continuous. 
:::

<!-- I threw the proof inside the theorem box, do we want to do this?--> 
<!-- I think we should keep proofs separate from the theorem box -->
:::{.proof}
Consider an arbitrary $V(x)$. Then, the Schrödinger equation reads:
$$
	-\frac{\hbar^2}{2m} \pdv[2]{\psi}{x} + V(x) \psi(x) = E \psi(x)
$$
We can now integrate this equation around an arbitrary point $[a - \epsilon, a + \epsilon]$:
$$
	-\frac{\hbar^2}{2m}\int_{a - \epsilon}^{a + \epsilon} \pdv[2]{\psi}{x} \ dx + \int_{a - \epsilon}^{a + \epsilon} V(x)
	\psi(x) \ d x = E \int_{a - \epsilon}^{a + \epsilon} \psi(x) \ d x
$$
The first term is just the derivative $\psi'(a + \epsilon) - \psi'(a - \epsilon)$, and the term on the right
hand side vanishes as $\epsilon \to 0$. So that leaves us with the equation:
$$
	\psi'(a + \epsilon) - \psi'(a - \epsilon) = \frac{2m}{\hbar^2} \int_{a - \epsilon}^{a + \epsilon} V(x)
	\psi(x) \ d x
$$
This brings us to the heart of the argument: if $V(x)$ is finite, then the integral on the right vanishes,
and we get:
$$
	\lim_{\epsilon\to0} \psi'(a + \epsilon) - \psi'(a - \epsilon) = 0,
$$ 
Which is precisely the definition of continuity in $\psi'$. However, if $V(x)$ is infinite, then
this equality fails. Hence, since our choice of $\psi$ and $V$ was arbitrary, we've proven that $\psi'$ is always continuous for finite potentials. $\blacksquare$ 
:::

:::{.remark}
This is also why we didn't have to consider continuity in $\psi'$ when dealing with the infinite square well.
:::

Now, we return to the delta function. In this case, since $V(x)$ is not finite, a discontinuity in $\psi'$ is
allowed, but the discontinuity at $x = 0$ will tell us more about the allowed energy:
$$
	\psi'(\epsilon) - \psi'(-\epsilon) = -\frac{2m}{\hbar^2} \int_{-\epsilon}^{\epsilon} a \delta(x) \psi(x) =
	-\frac{2ma}{\hbar^2} \psi(0) = -\frac{2ma}{\hbar^2}A
$${#eq-delta-function-integral}
The derivative of $\psi$ is:
$$
	\psi' = \begin{cases}
		A \kappa e^{\kappa x} & x < 0\\
		-A \kappa e^{-\kappa x} & x > 0
	\end{cases}
$$
As $x \to 0$, then $\psi' \to A \kappa$ for $x < 0$ and $A\kappa$ for $x > 0$. Substituting these values
into @eq-delta-function-integral gives us:
$$
	-2 A \kappa = -\frac{2ma}{\hbar^2}A \implies \kappa = \frac{ma}{\hbar^2}
$${#eq-3-kappa-second-definition}
We can finally solve for $E$! Recall all the way back (@eq-3-energy) that we defined $E$ in terms
of $\kappa$. But since we now know $\kappa$ in terms of other constants, we can finally pull out $E$:
$$
	E = -\frac{ma^2}{2 \hbar^2}
$$
Thus, we finally have the full solution for the delta function potential, for $E < 0$:
$$
	\boxed{\psi(x) = \frac{\sqrt{ma}}{\hbar} e^{-ma |x|/\hbar^2}, \quad E = - \frac{ma^2}{2\hbar^2}}
$${#eq-delta-well-decaying-sols}

:::{#fig-delta-well-bound-solutions fig-env="figure*" fig-pos="h"}
```tikz
\begin{tikzpicture}
  \draw[thick] (-2,0) node[left] {$0$} -- (-0.25,0) cos (-0.125,-1.5) sin (0,-3) node[below] {$-\infty$} cos (0.125,-1.5) sin (0.25,0) -- (2,0) node[right] {$V(x)$};
  \draw[very thick,blue!] (-2,0.1) node[above] {$\psi(x)$} parabola (0,1) (2,0.1) parabola (0,1);
\end{tikzpicture}
```
The delta function well bound state wavefunction solution visualized. The wavefunction is continuous everywhere, but its derivative is undefined at $x=0$.
:::

Now, we have to deal with the scattering states ($E > 0$). In this case, the solutions at $x < 0$ and $x > 0$
both admit plane wave solutions, one traveling to the left and another to the right:
$$
	\psi(x) = Ae^{-ikx} + Be^{ikx}, \quad k = \frac{2mE}{\hbar}
$$
The coefficients at this moment are undetermined, so we have four constants to deal with:
$$
	\psi_L(x) = Ae^{-ikx}+ Be^{ikx} \quad \psi_R(x) = Ce^{-ikx} + De^{ikx}
$$
We now know how to combine them into one big equation: we first enforce continuity at $x = 0$, which gives us
one relation:
$$A + B = C + D.$$
Now, we enforce continuity in the derivatives:
$$
	\begin{align*}
		\psi_L'(0) &=  ik(B - A) \\ 
		\psi_R'(0) &= ik (D - C) 
	\end{align*}
$$
Employing the same trick as in @eq-delta-function-integral, we get:
$$
	\psi'(\epsilon) - \psi'(-\epsilon) = ik(D - C) - ik(B - A) = \frac{2ma}{\hbar^2}\psi(0) = \frac{2ma}{\hbar^2}(A + B)
$$
We choose to use $\psi_L(0) = A + B$ for the last equality; the logic works the same with $\psi_R$.
There is a more compact way to write this equality; letting $\beta = \frac{ma}{\hbar^2 k}$ gives:
$$
	C - D = A(2 i \beta + 1) + B (2 i \beta - 1)
$$
So we have the following two equations for $A, B, C$ and $D$:
$$
\begin{align*}
	A + B &=  C + D \\
	D - C &=  B(1 - 2 i \beta) - A(1 + 2i \beta) 
\end{align*}
$$
But this is a big problem! We have 4 constants but only two equations, so we'll never be able to fully solve
for all constants. There is a way out, though; the key is to appeal to our intuition about what system
we're trying to describe. Say we're sending in a wave from the left. Then, it would not make sense to
consider a left-traveling wave in $\psi_R$, so that means that $C = 0$, and from here we solve for $A$
and $D$ in terms of $B$. Working out the algebra gets us the following:
$$
	A = -B \frac{i \beta }{1 + i \beta}, \quad D = \frac{B}{1 + i \beta}
$$
So what do we make of these solutions? The coeeficients $A$ and $D$ tell us the
amplitudes of the reflected and transmitted wave when sending in a wave with amplitude $B$ from the left. In
particular, we can now calculate quantities such as the *reflection coefficient*, which gives the
probability of reflection:
$$
	R = \frac{|A|^2}{|B|^2} = \frac{\left| -B \frac{i \beta}{1 + i \beta} \right|^2}{|B|^2} =
	\frac{\beta^2}{1 + \beta^2}
$$
Similarly, we can calculate a *transmission* coefficient: 
$$
	T = \frac{|D|^2}{|B|^2} = \frac{\left| \frac{B}{1 + i \beta} \right|^2}{|B|^2} = \frac{1}{1 + \beta^2}	
$$
What's nice is that we can verify that the reflection and transmission add up to 1 (a wave can either get
reflected or transmitted, without any other options):
$$
	R + T = \frac{\beta^2}{1 + \beta^2} + \frac{1}{1 + \beta^2} = 1\ \checkmark
$$
If we now bring back the earlier substitution for $\beta$, we can express these in terms of the energy itself:
$$
	\boxed{R = \frac{1}{1 + (2\hbar^2 E / ma^2)}}, \quad \boxed{T = \frac{1}{1 + (ma^2 / 2\hbar^2 E)}}
$${#eq-tr-coefficients-delta-well}
And that's the full solution to the delta well! It's blatantly apparent that this derivation is
*very* non-classical: it predicts that a potential *well* has the chance to scatter a particle despite the
particle having a positive energy.

***

At this point, let's talk briefly about the delta potential *barrier*, which is basically the same potential but positive: 
$$V(x) = a \delta(x)$$
Similar to the well, we offer a (crude) visualization below.

:::{#fig-delta-barrier fig-env="figure*" fig-pos="h"}
```tikz
\begin{tikzpicture}
  \draw[thick] (-2,0) node[left] {$0$} -- (-0.25,0) cos (-0.125,1.5) sin (0,3) node[above] {$\infty$} cos (0.125,1.5) sin (0.25,0) -- (2,0) node[right] {$V(x)$};
\end{tikzpicture}
```
The delta function barrier potential. Similar to the delta well, the width and height are exaggerated to appear more like a barrier.
:::

While it may seem like we need to do the math all over again, we actually don't: switching the sign only
changes the behavior at $x = 0$, so our scattering state remains the same. What does change though is the
bound state. To see why, recall that for the bound state, $\kappa$ was defined as (@eq-3-energy):
$$
	\kappa = \frac{\sqrt{-2 m E}}{\hbar}
$$
For negative energies, this is guaranteed to be *real* and *positive*. However, if we look at our other definition
of $\kappa$ in terms of $a$ and $m$ (@eq-3-kappa-second-definition):
$$
	\kappa = \frac{ma}{\hbar^2}
$$
If $a < 0$, this solution for $\kappa$ becomes inconsistent with the first, and hence such a bound
state cannot exist. However, the scattering solutions are unaffected because we don't have an equivalent
restriction on $k$.  

:::{.remark}
It is interesting to note that because the transmission and reflection are dependent on $a^2$, these
quantities remain the same regardless of a well or a barrier! This is quite striking -- for one, the
mere fact that two different potentials yield the same reflection and transmission is fascinating.
Moreover, the fact that a potential well can induce a reflection is also peculiar. Classically, this would
be the equivalent of throwing a ball over a well and it having a chance to bounce right back, but in
quantum mechanics, such a phenomenon is totally allowed!
:::

### The Potential Step {#sec-potential-step}
Here, we will consider a potential represented by a wall of finite height:
$$
	V(x) = \begin{cases}
	0 & x < 0\\
	V_0 & x > 0
	\end{cases}
$$
It is called the *potential step*, because it functions exactly like a step function in mathematics.

:::{#fig-potential-step fig-env="function*" fig-pos="h"}
```tikz
\begin{tikzpicture}
\draw[thick] (-2,0) node[left] {$0$} -- (0,0) node[below] {$V(x)$} -- (0,2) -- (2,2) node[right] {$V_0$};
\end{tikzpicture}
```
The step potential. This is like one half of a finite well, which we will analyze a bit later.
:::

There are two different kind of states to consider: $0 < E < V_0$ and $E > V_0$ (the $E < 0$ state does
not exist). Let's consider the $E < V_0$ state first.

To the left of the barrier, we have a scattering state, but to the right we have a *decaying* state, since $E - V_0$ is negative. This is because inside the barrier, Schrödinger's equation reads:
$$
	\pdv[2]{\psi}{x} = (E - V_0)\psi
$$
Following the same substitution for $k$ as in @sec-free-particle, we get:
$$
	k = \frac{\sqrt{2m(E - V_0)}}{\hbar} = \frac{i\sqrt{2m (V_0 - E)}}{\hbar}
$$
Since $k$ is purely imaginary, this turns the oscillatory $e^{ikx}$ into an ordinary decaying exponential. Combining
this with the oscillatory solution to the left of the barrier yields the following solution for $\psi$: 
$$
	\psi\left( x \right) = \begin{cases}
	Ae^{ikx} + Be^{-ikx} & x < 0\\
	Ce^{\kappa x} + De^{-\kappa x} & x > 0
	\end{cases}
$$
Here, $k$ and $\kappa$ are defined as:
$$
	k = \frac{\sqrt{2mE}}{\hbar}\quad \kappa = \frac{\sqrt{2m(V_0 - E)}}{\hbar^2}
$$
Again, we're faced with a situation where continuity alone doesn't give us enough equations to fully solve
for all four constants,
forcing us to be more specific about the problem to eliminate some variables.

Firstly, let's say that our wave is coming in from the left. This would mean that inside the barrier, 
an exponentially *growing* solution would not make sense, and therefore we can set $C = 0$. Now, we 
have enough equations to solve for $B$ and $D$ in terms of $A$. In particular, at $x = 0$, the continuity 
constraints in $\psi$ and $\psi'$ gives us the following system of equations:
$$
	\begin{align*}
	A + B &=  D \\ 
	ik(A - B) &= -\kappa D 
	\end{align*}
$$
Now, expressing $B$ and $D$ in terms of $A$ (remember, $A$ is our incident wave amplitude, so it makes sense
to solve in terms of $A$) just requires some algebra, and ultimately gets us the relations:
$$
	B = \frac{ik + \kappa}{ik - \kappa}A, \quad D = \frac{2ik}{ik - \kappa} A
$$
Here, we can calculate the reflection coefficient as we did with the delta function potentials:
$$
	R = \frac{|B|^2}{|A|^2} = \left| \frac{ik + \kappa}{ik - \kappa} \right|^2 = 1
$$
This tells us that <u>the entire amplitude of the wave is reflected</u>. This makes sense; since the barrier is
infinitely thick, any wave will be fully reflected back. As we'll see in @sec-potential-barrier, when the
barrier is only finitely thick, we will get a transmitted wave, called *tunnelling*[^quantum-tunneling]. 

:::{.warning}
It's natural to wonder: if the entire wave is reflected, then why is the wavefunction nonzero inside the
barrier? Doesn't this imply that there is a nonzero probability for the particle to be *inside* the barrier,
and thus not be reflected? 

The answer to this question is quite subtle. Firstly, decaying solutions don't carry any energy, as their
probability current turns out to be zero. Hence, all the energy must be reflected back. But, perhaps this
isn't a satisfying answer, in which case there another solution.

Suppose we *were* able to measure the particle inside the barrier. In that case, the decaying solution has a characteristic length of $\frac{1}{\kappa}$, so the variance in position is 
$$\Delta x \sim \frac{1}{\kappa}.$$
But, by the position-momentum uncertainty relation: 
$$
	\Delta p_x \geq \frac{\hbar}{\Delta x} = \hbar \kappa = \sqrt{2m(V_0 - E)}
$$
Plugging this into the energy:
$$
	\Delta E = \frac{(\Delta p_x)^2}{2m} \geq V_0 - E
$$
This tells us that, by measuring the particle inside the barrier, we've inadvertently *scattered* said
particle, and it's no longer in the barrier! So, it's physically impossible to measure the particle to be
inside the barrier, no matter how careful we are.    
:::

Now we consider the second solution, the $E > V_0$ case. In this case, both $x < 0$ and $x > 0$ admit
scattering solutions, but with different wavenumbers:
$$
	\psi(x) = \begin{cases}
	Ae^{ikx} + Be^{-ikx} & x < 0\\
	C e^{ikx} + De^{-ikx} & x > 0
	\end{cases}, \quad \quad k = \frac{\sqrt{2mE}}{\hbar}, \quad k' = \frac{\sqrt{2m (E - V_0)}}{\hbar}
$$
Again, we impose a physical constraint of a particle incident from the left. This kills the left
travelling wave in $x > 0$, so $D = 0$. Using the continuity constraints again, we get the following
relation:
$$
	B = \frac{k k'}{k + k'}A, \quad C = \frac{2k}{k + k'}A 
$$
This algebra follows very similarly from the previous examples, so we'll skip showing it here. With this, we
can now calculate the reflection and transmission probabilities:
$$
  \boxed{R = \frac{|B|^2}{|A|^2} = \frac{\left[ 1 - \left( 1 - \frac{V_0}{E} \right)^{1 / 2} \right]^2}{\left[ 1 +
	\left( 1 - \frac{V_0}{E} \right)^{1 / 2}\right]^2}}, \quad \boxed{T = \frac{4\left( 1 - \frac{V_0}{E} \right)^{1 /
	2}}{\left[ 1 + \left( 1 - \frac{V_0}{E} \right)^{1 / 2} \right]^2}}
$$
We encourage the reader to verify on their own that $R + T = 1$.

<!-- I may be overusing remarks; decide for yourself which of these should be left in external environments
-->
:::{.remark}
Just like the delta potential well, we find that even though the particle's energy can be higher than the step, there's *still* get some reflection regardless, which is a fundamentally non-classical result.
:::

### The Potential Barrier {#sec-potential-barrier}
This potential is similar to that of the potential step, but this time it's a finitely long wall:
$$
	V(x) = \begin{cases}
	0 & x < 0\\
	V_0 & 0 < x < a\\
	0 & x > a
	\end{cases}
$$
Below is a visualization.

:::{#fig-potential-barrier fig-env="figure*" fig-pos="h"}
``` tikz
\begin{tikzpicture}[scale=2]
	\draw[thick] (-1, 0) -- (0, 0) node[below] {$0$} -- (0, 1) node[left] {$V_0$} -- (1, 1) -- (1, 0) node[below] {$a$} -- (2, 0);
\end{tikzpicture}
```
The potential barrier. The maximum height of the barrier is $V_0$, and its width is $a$.
:::

Here, there are two cases we need to consider: $E > V_0$ and $0 < E < V_0$. For $E < 0$, we get an infinitely
decaying solution, which is to say that $\psi = 0$ in that case. Let's start with the $0 < E < V_0$ case,
which (as we mentioned before) will lead to a tunnelling situation. We'll split up the wavefunctions into
three regions:

1. To the left of the wall: $x < 0$ 
2. Inside the wall: $0 < x < a$
3. To the right of the wall: $x > a$

The respective wavefunctions we solve for will be labeled $\psi_1$, $\psi_2$, and $\psi_3$, according to
the above numbering. Starting off with $x < 0$, we have the same plane wave solution as before: 
$$
	\psi_1(x) = Ae^{ikx} + Be^{-ikx},
$$
With $k = \frac{\sqrt{2mE}}{\hbar}$ as before. The same goes for the right:
$$
	\psi_3(x) = Ce^{ikx} + De^{-ikx}
$$
Now let's look at the Schrödinger equation for $0 < x < a$:
$$
	-\frac{\hbar^2}{2m}\pdv[2]{x} \psi + V_0 \psi = E\psi
$$
Moving the $V_0$ to the right gives:
$$
	-\frac{\hbar^2}{2m}\pdv[2]{x}\psi = (E - V_0)\psi
$$
Since $E < V_0$ here, then we have exponentially decaying solutions inside the wall:
$$
	\psi_2(x) = Fe^{\kappa x} + Ge^{-\kappa x},
$$
With $\kappa = \sqrt{2m(V_0 - E)}/\hbar$. Unlike the potential step, though, we can't simply eliminate the
exponentially growing solution by setting $F = 0$: because the barrier isn't infinitely long, the
exponentially growing solution is actually allowed. However, we can still eliminate $D$, by considering a particle
incident from the left. 

Now, because we have split $\psi$ into three wavefunctions, we need to stitch them together by enforcing
continuity in $\psi$ and $\psi'$ at $x = 0$ *and* $x = a$. The $x = 0$ conditions are:
$$
	\begin{align*}
		A + B &=  F + G \\ 
		ik(A - B) &=  \kappa (F - G) 
	\end{align*}
$$
Similarly, the $x =a$ ones are:
$$
	\begin{align*}
		Ce^{ika} &= Fe^{\kappa a} + Ge^{-\kappa a}\\
		ik e^{ika} &= \kappa (Fe^{\kappa a} - Ge^{-\kappa a})
	\end{align*}
$$
From here, we can then solve for $\frac{B}{A}$ and $\frac{C}{A}$, which will give us the reflection and
transmission coefficients. The algebra here becomes cumbersome and fairly unilluminating, so we summarize the
results with hyperbolic trigonometric functions:
$$
	\boxed{R = \left[ 1 + \frac{4 E(V_0 - E)}{V_0^2 \sinh(ka)} \right]}, \quad \boxed{T = \left[ 1 + \frac{V_0^2
	\sinh^2(\kappa a)}{4E(V_0 - E)} \right]}
$${#eq-potential-barrier-bound-solutions}
Now, we turn our attention to the $E > V_0$ case. Here, all three regions have scattering solutions, but $k$
is different above the barrier because of $V_0$:
$$
	\psi = \begin{cases}
	Ae^{ikx }+ Be^{-ikx} & x < 0\\
	Fe^{ik'x} + Ge^{-ik'x} & 0 < x < a\\
	Ce^{ikx} + De^{-ikx} & x> a
	\end{cases}
$$
Again, following the same algebra yields:
$$
	\boxed{R = \left[ 1 + \frac{4E(E - V_0)}{V_0^2 \sin^2(k' a)} \right]^{-1}}, \quad \boxed{T = \left[ 1 + \frac{V_0^2
	\sin^2(k'a)}{4E(E - V_0)} \right]^{-1}}
$${#eq-potential-barrier-scattering-solutions}

We want to focus on the physics and not the algebra so we won't go into detail, but it really does
work in the same way we've always been doing it: consider a left-incident wave, set $D = 0$, then 
eliminate $F$ and $G$ and solve for $\frac{B}{A}$ and $\frac{C}{A}$. Finally, square these to get the
reflection and transmission coefficients. 

:::{.remark}
Speaking of focusing on the physics, notice that because the transmission term has a $\sin^2(k'a)$ term, it
means that there are some configurations where the $T = 1$ and $R = 0$, yielding perfect transmission! 
::: 

### Finite Square Well 
The final potential we'll analyze in this chapter is the finite square well. This is similar to the
infinite square well, but this time our walls are finitely tall. As we'll see, this gives us a first glimpse
into why the Schrodinger equation is difficult to solve analytically. Mathematically, we will express this
potential as:
$$
	V(x) = \begin{cases}
	-V_0 & -a < x < a\\
	0 & \text{otherwise}
	\end{cases}
$$
This potential is functionally the inverse of the potential barrier that we studied above, though our
treatment will look a little different.

:::{#fig-finite-square-well}
``` tikz
	\begin{tikzpicture}[scale=1.5]
		\draw[thick] (-2, 2) node[left] {$0$} -- (-1, 2) -- (-1, 0) node[below] {$-a$} -- (1, 0) node[below] {$a$} node[right] {$-V_0$} -- (1, 2) -- (2, 2);
	\end{tikzpicture}
```
The finite square well. Here, the depth of the well is $V_0$, but the length is given as $2a$ (as opposed to
$a$, like in the case of the *infinite* square well) for the
purposes of making a symmetric argument easier.
:::

There are two cases we have to consider: $-V_0 < E < 0$ (bound state) and $E > 0$ (scattering state).

Starting with the first case, let's again break up $\psi$ into two parts: inside and outside the well. Inside
the well, the Schrödinger equation is written as:
$$
	\pdv[2]{\psi}{x} + \alpha^2 \psi = 0,
$$
With $\alpha$ defined as:
$$
	\alpha = \left[ -\frac{2m}{\hbar^2} (V_0 + E) \right]^{1 / 2}
$$
This is a scattering solution, since the energy of the particle is larger than $-V_0$, giving us
oscillatory solutions. For reasons that will become clear in a moment, we'll express $\psi$ in this region in
terms of sines and cosines:
$$
	\psi = A\cos(\alpha x) + B \sin(\alpha x), |x| < a
$$
Outside the well, we have decaying solutions since $E < 0$. The Schrödinger equation in this region reads as:
$$
	\pdv[2]{\psi}{x} - \beta \psi(x) = 0,
$$
With $\beta$ defined as:
$$
	\beta = \left( -\frac{2mE}{\hbar^2} \right)^{1 / 2}
$$
Now, we will leverage the following theorem to make our lives easier:

:::{.theorem #thm-1d-symmetric-potential}
# Wavefunction for Symmetric Potentials
If a potential $V(x)$ is symmetric (ie, $V(x) = V(-x)$ for all $x$), then its wavefunction is also symmetric (ie, $\psi(x) = \psi(-x)$ for all $x$).   
:::
:::{.proof}
Suppose first that $\psi(x)$ satisfies the Schrödinger equation for $V(x)$. That is, $\psi(x)$ is a solution
to:
$$
	-\frac{\hbar^2}{2m} \pdv[2]{\psi(x)}{x} + V(x) \psi(x) = E \psi(x) 
$${#eq-symmetry-proof-1}
Now, consider $\psi(-x)$:
$$
	-\frac{\hbar^2}{2m} \pdv[2]{\psi(-x)}{x} + V(-x)\psi(-x) = E\psi(-x)
$$
Since $V(-x) = V(x)$, then:
$$
	-\frac{\hbar^2}{2m}\pdv[2]{\psi(-x)}{x} + V(x) \psi(-x) = E\psi(-x)
$$
Since this differential equation is the same as the original equation (@eq-symmetry-proof-1), then
$\psi(-x)$ is also a solution. As such, any even and odd linear combination of these will
also be a solution. That is, the functions:
$$
	\begin{align*}
		\phi(x) &= \psi(x) + \psi(-x)\\
		\phi'(x) &= \psi(x) - \psi(-x) 
	\end{align*}
$$
Are also solutions. Therefore, we can always take $\psi$ to be even or odd. $\blacksquare$
:::

In our case, the finite square well does indeed satisfy this property, and so we can focus on looking for
even and odd solutions. This makes our lives much easier, since it narrows our focus to one
set of boundary conditions at $x = a$ instead of two. 

Let's start by considering even $\psi$. Then, the wavefunction is:
$$
	\psi(x) = \begin{cases}
		B \cos(\alpha x) & 0 < x < a\\
		Ce^{-\beta x} & |x| > a
	\end{cases}
$$
Now, imposing boundary conditions at $x = a$ gives:
$$
	\begin{align*}
	\psi: \ A \cos(\alpha x) &= Ce^{-\beta a}\\
	\psi': \ -\alpha A \sin(\alpha a) &= -\beta Ce^{-\beta a}
	\end{align*}
$$
Dividing one equation by the other gives:
$$
	\alpha \tan (\alpha a) = \beta
$$
Similarly, for the odd solutions, we kill the $B \cos(\alpha x)$ term in $0 < x < a$ and the decaying
solution remains the same. Applying the same boundary conditions gives the equation:
$$
	\alpha \cot(\alpha a) = -\beta
$$
Both of these equations represent the condition for the allowed energies of the system. That is, for a given
$a$ and $V_0$, these equations tell us which energies $E$ are allowed. What's interesting about these equations is that they're
not analytically solvable, so we can only solve them numerically. 

:::{.remark}
Hopefully working out the these bound states gives a better appreciation for why the Schrödinger
equation is typically a very difficult equation to solve analytically. The potential we're dealing with here
is hardly anything complicated -- it's just a simple square well of finite depth, yet we're already
having to resort to numerical methods to get the allowed energies. 

As is easy to guess, this becomes a general trend as we move toward more complicated potentials. Rarely are any
of these potentials analytically solvable, so we have to resort to numerical methods or find a way to
approximate the solutions. This latter idea is the central idea of the second part of this book <!--TODO: Insert
part 2 reference when written-->.
:::

Now let's deal with the scattering solution. This ends up working out similarly to the delta potentials, in that the math is functionally identical. For the left-incident particle, we have:
$$
	\psi(x) = \begin{cases}
	Ae^{ikx} + Be^{-ikx} & x < -a\\
	Fe^{ik'x} + Ge^{-ik'x} & -a < x < a\\
	Ce^{ikx} & x > a
	\end{cases}
$$
There is no left-travelling wave at $x > a$, since we are considering a left-incident wave. Notice that this
is exactly the same situation as the finite potential barrier, except $k'$ is *slightly* different, in that
we make the swap $V_0 \to -V_0$. All the algebra remains the same, so we can just copy over the reflection
and transmission coefficients we got from there and make this simple edit to $V_0$:[^finite-square-well]
$$
  \boxed{R = \left[ 1 + \frac{4E(E + V_0)}{V_0^2 \sin^2(2k'a)} \right]^{-1}}, \quad \boxed{T = \left[ 1 + \frac{V_0^2
	\sin^2(2k'a)}{4E(V_0 + E)} \right]^{-1}}
$$

## Time-Dependent Schrodinger Equation
So far, we've been dealing with the time-*independent* Schrodinger equation, which doesn't account for any
time evolution. In this section, we will look at how we can transform a solution to the
time-independent solution into one that incorporates time dependence. While this may seem complicated at first,
the trick actually turns out to be very simple. 
   
### Separable solutions
To begin, let's take a look at the time-dependent Schrödinger equation:
$$
	i\hbar \pdv{\Psi}{t} = -\frac{\hbar^2}{2m} \pdv[2]{\Psi}{x} + V\Psi
$$
Because we deal with time-independent potentials, it means that we can actually solve this equation by method
of *separation of variables*. That is, we look for solutions that are products of time-independent and
space-independent components:  
$$
	\Psi(x, t) = \psi(x) \phi(t)
$$
Solving for $\psi(x)$ was pretty much all that we've been doing in this chapter so far. Now, given a
$\psi(x)$, what is the appropriate $\phi(t)$ to tack on so that $\Psi(x, t)$ is a solution to the
time-dependent equation? Let's first plug this separable solution back into the Schrödinger equation:
$$
	i\hbar \psi \dv{\phi}{t} = -\frac{\hbar^2}{2m} \dv[2]{\psi}{x} \phi + V \psi \phi
$$
Dividing through by $\psi \phi$:
$$
	i\hbar \frac{1}{\phi} \dv{\phi}{t} = -\frac{\hbar^2}{2m} \frac{1}{\psi} \dv[2]{\psi}{x} + V
$${#eq-separable-equation}
Now comes a crucial argument: the left-hand side is a function of $t$, while the right-hand side is a function of
$x$. Therefore, in order for this equation to hold, both sides **must** be constant. Otherwise, we could
change one side of this equation without changing the other, violating the equality. Therefore, we can set
both sides to be constant:
$$
	i\hbar \frac{1}{\phi} \dv{\phi}{t} = E \implies \dv{\phi}{t} = -\frac{iE}{\hbar}\phi
$$
This is now a simple differential equation for $\phi$, which gives solutions:
$$
	\phi(t) = e^{-iEt / \hbar}
$$
That's our time dependence! All that needs to be done now is tacking this onto every solution to the spatial
$\psi(x)$, and we have the general solution $\Psi(x, t)$.

:::{.remark}
As a side note, setting the right hand side of @eq-separable-equation to $E$ gives the time-independent Schrödinger equation!
:::

At this point, it's natural to ask if we've covered *all* possible solutions this way. After all, the
condition that $\Psi(x, t)$ be separable is a fairly restrictive one. As it turns out, whenever the
Hamiltonian is time-independent and $\hat{H}$ admits a complete set of energy eigenfunctions, then the
separable solutions are enough to describe any general solution. Here, completeness refers to the condition
that any square-integrable function (i.e. any function in our Hilbert space $\mathcal{E}$) 
can be written as a linear combination of these eigenfunctions. Since every solution $\Psi(x, t)$ must be
square-integrable, then this completeness condition is all we need to guarantee that we've covered all
solutions.  

:::{.remark}
This completeness condition is actually not as restrictive as one might think -- all the
Hamiltonians we will deal with in this book satisfy this completeness, even though we'll be looking at some
pretty complicated potentials later on!   
:::

### Final Note
<!-- idk if we'll cover SHO immediately after this so feel free to adjust this final note depending on
exactly what comes next -->
Though we will analyze some additional potentials in one dimension later on, they will be significantly more
complicated than what we've covered above and will require their own separate chapters for a full treatment.
As such, we conclude the chapter on one-dimensional mechanics here. Our next task will be generalizing to
three dimensions and moving on to one of the most crucial problems in quantum mechanics: that of the
*harmonic oscillator*. More on that soon!

[^ode]: This stands for *ordinary differential equation*; here, "ordinary" refers to how our function is
single-variable. Once we introduce higher dimensions or time dependence, our derivatives will be partial,
meaning we will have a *partial* differential equation (or PDE).

[^delta-function]: Formally, $\delta(x)$ is called a *distribution* rather than a function, but we won't
	worry too much about this distinction. It's good enough for our purposes to treat $\delta(x)$ as a
	function that is zero everywhere except at $x = 0$ where it equals infinity, and that its integral over all
	space is equal to one. 

[^scatter-decay]: In case you're wondering why we haven't dealt with the sign of $E$ until now, it's because we didn't
	need to. In the free particle example, a particle with negative energy and admits a decaying solution
	would blow up at either $\infty$ or $-\infty$, which are not normalizable and thus inadmissible. A
	negative energy state isn't admissible in the infinite square well potential either, since there's no way
	for an exponentially decaying function to be identically zero as is required to match the boundary
	condition on either side of the well.

[^quantum-tunneling]: This is the very elusive *quantum tunneling* that we hear a lot about in science
fiction; it is possible for a particle to transmit through a finite-width barrier and pop out on the other
end (hence the "tunneling"). Since the step potential is infinitely thick, however, the particle cannot
tunnel through to the other side.

[^finite-square-well]: We also have to make the change $a \to 2a$ compared to the square barrier since $a$
	was the width of the barrier, but $a$ as defined in the finite well is only half the width of the well.
