<!-- working title; maybe something better would work here? -->
# From Classical Quantities to Quantum Operators {#sec-quantum-from-classical}
We laid the theoretical framework underpinning quantum mechanics in the formalism and applied to the real 
world with the postulates. At long last, we are able to start developing some physics.

Why all this setup? Many undergraduate courses in quantum mechanics will skip over all of this formal 
development at the beginning in favor of jumping straight into working with the wavefunction and utilizing the 
Schrödinger equation to solve basic problems. This choice is typically made to avoid adding needless complexity 
and to prevent the technical mathematical 
details from getting in the way of a basic physical intuition. As a matter of fact, this is precisely how we 
learned quantum mechanics initially, before supplementing the finer mathematical formalism in later graduate courses.

We considered following suit and also omitting these details to jump straight into the physics, but decided to include this 
for a few reasons. Primarily, we did this because **this is not a university course on quantum mechanics**. We are not bound 
by any time constraints and do not need to adhere to any explicit schedule, so the reader can take as much time as is 
required for everything to make sense. Since we don't need to move through a unit within a week or two, there’s no longer 
a pressing need to omit certain details in the name of expediting the material.

:::{.remark}
This is not in any way suggesting that the way undergraduate courses structure quantum mechanics is wrong. 
Rather, since we are not bound by the same restrictions that an undergraduate course is, we can take certain liberties in 
material presentation.
:::

Since we don't have the same time restrictions, we can build up the material a bit more rigorously and mathematically. 
Even though this rigorous development requires a certain level of mathematical maturity and is ultimately more challenging 
for a first reader than jumping straight into the physics would be, we feel that it is extremely satisfying to see all of 
the operators and equations we use pop out directly from first principles and experimental results. 
This way, we don't need to simply state the form of an operator without justification simply because we want 
to practice using it. Thus, we hope you have beared with us while we laid all the pieces in place.

:::{.warning}
As we warned at the beginning of the Formalism chapter, there is a *lot* of mathematics involved in the 
development of a formal framework for a physical theory. In particular, this chapter will also make use of
classical objects like the Hamiltonian as a foundational object in the derivation of quantum operators, while
omitting many details about what they represent. We do recognize that this diminishes the satisfaction 
from arriving at a result, but we do feel that these omissions are a worthy price to pay so as to keep our discussion focused 
on the quantum mechanics. If the reader wishes to gain a more solid 
mathematical footing before attempting to understand certain parts of our presentation, that's totally fine! 
We will wait here for you to return. It is our hope, though, that we do a sufficiently good job of presenting whatever mathematics 
is necessary throughout the relevant chapters and accompanying appendices at the back.
:::

## Position Representation
Let’s start with figuring out how to describe a particle’s position in quantum mechanics. For simplicity, we
will start with the 1-dimensional case, then address 3 dimensions later on. Let’s also assume that a
particle’s position in space (call it $x$) can be measured, and these measurement results are continuous
(since space isn’t discretized). Let’s then denote the operator associated with measuring the position
$\hat{x}$ and any eigenkets of the position $\ket{x}$. Thus, our eigenvalue problem takes the following form:
$$
	\hat{x}\ket{x} = x\ket{x}
$$

:::{.notation}
We will see much more of this hat notation moving forward; an operator will typically be denoted with a hat on top of it 
to indicate that it is an operator rather than a variable. The main exceptions will be those operators labeled with 
*capital* letters, since those are harder to confuse for variables or other mathematical objects.
:::
Since we are dealing with a continuous spectrum and nondegenerate eigenkets (positional values can only
correspond to a unique position), the inner product between two kets $\ket{x_1}$ and $\ket{x_2}$ is,
according to [REFERENCE HERE] is given by:
$$
	\braket*{x_1}{x_2} = \delta(x_1 - x_2)
$$
The resolution of the identity is then:
$$
	\int_{-\infty}^{\infty}\ketbra{x}dx = 1
$$
Now, let $\ket{\psi}$ represent a normalized pure state for our system, and $I=[x_0,x_1]$ be some interval on
the $x$-axis. In this case, the projector onto the interval looks like this:
$$
	P_I = \int_{x_0}^{x_1}\ketbra{x}dx
$$
Then, the probability postulate tells us that the probability of measuring some positional value within this
interval is given by the following expectation value:
$$
	\mathrm{Prob}(x_0\leq x\leq x_1) = \expval{P_I}{\psi} = \int_{x_0}^{x_1}\braket{\psi}{x}\braket{x}{\psi}dx
$$
Now, that last expression looks like we're taking some squared norm. To make our lives easier (and to make
this expression look more like an integral expression wherein we're actually integrating a function), let's
finally define the *positional wavefunction* $\psi(x)$:

:::{.definition #def-positional-wavefunction}

# Positional Wavefunction
The *wavefunction*, denoted $\psi(x)$, encodes the state in configuration space and is given by the following inner product: 
$$
	\psi(x) = \braket{x}{\psi}
$$
:::

Then, our probability becomes:
$$
	\mathrm{Prob}(x_0\leq x \leq x_1) = \int_{x_0}^{x_1}|\psi(x)|^2dx = \int_{x_0}^{x_1}\psi^*(x)\psi(x)dx
$$
Here, we see that the squared norm of the positional wavefunction encodes the probability density of finding the
particle at a given point in space. Now, we finally have a way to go from kets to functions!

Can we go the other way? No problem! If we multiply both sides of the resolution of the identity by
$\ket{\psi}$, we get a representation of the ket:
<!-- do we want to encode this in a lemma or leave it outside any tcolorbox and just keep it boxed? -->
$$
	\ket{\psi} = \int \ket{x}\braket{x}{\psi}dx \implies \boxed{\ket{\psi} = \int  \ket{x}\psi(x)dx}
$$

Now that we have a way to convert between ket formalism and functional notation, we also have a way to
describe the inner product between two kets $\ket{\psi}$ and $\ket{\phi}$ by once again inserting the
resolution of the identity between them:
$$
	\braket{\psi}{\phi} = \int \braket{\psi}{x}\braket{x}{\phi}dx = \int \psi^*(x)\phi(x)dx
$$


### Generalization to 3 Dimensions
This formalism extends quite easily to three dimensions, where we simply have to consider three separate
positional components $(x,y,z)$.

:::{.notation}
For the sake of consistency (and because it will allow us to make more efficient use of index notation),
instead of labeling the components $(x,y,z)$, we will label them $(x_1,x_2,x_3)$. This way, we can compare
arbitrary spatial components $x_i$, $x_j$ without having to find some random combination of $x$, $y$, and
$z$.
:::

In this case, rather than simply measuring the overall position, we will have separate operators for
measuring each component of the position: $\hat{\mathbf{x}} = (\hat{x}_1, \hat{x}_2, \hat{x}_3)$. This is
what's known as a "vector operator", since it's a vector comprised of different operators. We will assume
that the components all commute with each other (since they're orthogonal and shouldn't affect each other's
measurements):
$$
	[\hat{x}_i,\hat{x}_j] = 0
$$
So, we now can write three separate eigenvalue problems, conveniently condensed into one using index
notation: 
$$
	x_i\ket{\mathbf{x}} = x_i\ket{\mathbf{x}}
$$
Just as with the one-dimensional case, we have a similar resolution of the identity:
$$
	1 = \int \ketbra{\mathbf{x}}d^3\mathbf{x}
$$
Then, our wavefunction-ket transformations translate seamlessly from the one-dimensional case:
$$
	\psi(\mathbf{x}) = \braket{\mathbf{x}}{\psi}, \quad \ket{\psi} = \int \ket{\mathbf{x}}\psi(\mathbf{x})\ d^3\mathbf{x}
$$
Finally, the probability density of finding the particle in some region $R$ in 3-dimensional space becomes a
multivariate integral:
$$
	\mathrm{Prob}(\mathbf{x} \in R) = \int_R|\psi(\mathbf{x})|^2 \ d^3\mathbf{x}
$$

### The Position Operator
What we've accomplished thus far amounts to representing an arbitrary ket state in configuration space; this,
at its core, is what the wavefunction is. What happens now when we try to represent the wavefunction of an
operator's action on a ket? For instance, if $\ket{\psi}$ corresponds to $\psi(x)$, what wavefunction does
$\hat{x}\ket{\psi}$ correspond to? Let's label the resultant ket $\ket{\phi} = \hat{x}\ket{\psi}$ and find
its wavefunction representation:
$$
	\phi(x) = \braket{x}{\phi} = \braket{x}(\hat{x}\ket{\psi}) = \mel{x}{\hat{x}}{\psi} 
	= (x\bra{x})\ket{\psi}= x\braket{x}{\psi} = x\psi(x)
$$
Interestingly, acting the $\hat{x}$ operator on a ket $\ket{\psi}$ just multiplies the corresponding
configuration space wavefunction by $x$:
$$
	\boxed{(\hat{x}\psi)(x) = x\psi(x)}
$${#eq-position-definition}
Thus, in configuration space, $\hat{x}$ is represented by multiplication of the wavefunction by $x$. This is
our position operator. Generalizing to three dimensions is easy:
$$
	(\hat{x}_i\psi)(\mathbf{x}) = x_i\psi(\mathbf{x})
$$

:::{.remark}
There's one lingering question here: what's the physical meaning of the position eigenkets $\ket{x}$,
$\ket{\mathbf{x}}$? As we discovered before, these are not normalizable, which means they cannot belong to
any relevant Hilbert space that we could make use of. This isn't actually a big deal for us, because we'll
never measure the position of a particle *exactly*; rather, we will localize it to some region of space, and
the eigenkets of position are simply an idealized variant where the size of the region is sent to $0$ in the
limit. 

In general, measuring the position of a particle is an inherently nonrelativistic concept, since localizing
the position to smaller and smaller regions will blow up the momentum (because of the uncertainty relation
which we'll quantify more explicitly later), until it eventually reaches relativistic ranges. As such, the concept of a position
operator and measuring a particle's position will be relegated mostly to nonrelativistic quantum mechanics
(which we'll be developing in the first two parts of this book), with relativistic quantum mechanics
(explored in Part III) requiring a fundamentally different treatment.
:::

## Momentum Representation {#sec-momentum-operator}
Now that we've established how to appropriately make positional measurements, a natural next step is to 
understand how to quantify momentum. Firstly, as it's a quantity we can measure in experiment, then by our third
postulate the momentum should have an associated operator, call it $\hat{p}$. Clearly, given eigenstates
$\ket{p}$, the momentum operator acts on these states just as $\hat{x}$ does on $\ket{x}$:
$$
	\hat{p} \ket{p} = p \ket{p}
$$
This is well defined, but what does $\hat{p}$ do to states $\ket{x}$, the states that live in configuration
space? Since $\ket{x}$ are eigenstates of $\hat{x}$ but not necessarily eigenstates of $\hat{p}$ -- in fact, they
*cannot* be, as we'll soon show -- what $\hat{p}$ does to $\ket{x}$ is not immediately obvious.

### The Generator of Translations

Before we begin, one question we should ask ourselves is, how *should* the momentum operator $\hat{p}$ behave? 
In a sense, there is no right answer to this: one can define the "momentum operator" however they please, but
that definition may not lead to any meaningful physics. Our goal then, is to find a definition of momentum
that *does* give us interesting physics, and without any better reference point, why not pick the momentum
$\hat{p}$ such that it plays the same role as its classical analogue?
   
Following this reasoning, now our goal is clear: we want to define the momentum operator $\hat{p}$ such that
it fulfills the same role as $p$ does in classical mechanics. So, what role does $p$ fundamentally fulfill in
classical mechanics? As it turns out $p$ is also called the *generator of translations*, and this fact gives
us the proper springboard to define its quantum counterpart.

To begin, consider a scalar function $f(x, p)$ parametrized by position and momentum, and now consider a
translation by $a$ units. We can then write this new function $f(x - a, p)$ in terms of $f(x, p)$ and its
derivatives:
$$
	f(x - a, p) = f(x, p) + a \pdv{f}{x} + \frac{a^2}{2} \pdv[2]{f}{x} (x, p) + \dots
$$
If we now make use of Poisson brackets (more on these in @sec-poisson-bracket), it is possible to write
this as: 
$$
	f(x - a, p) = f(x, \dot x), + a \{p, f\} + \frac{a^2}{2} \left\{ p, \left\{ p, f \right\} \right\} +
	\dots 
$$
where we can see that on the right, the translation operation can be built up directly using only $p$, and
this is why we call $p$ the classical generator of translations.

At first, it may feel contrived to consider a function specifically parametrized by $x$ and $p$, but there is a good
reason for this. In classical mechanics, the *Hamiltonian* (an object we will also soon quantize) is a mathematical object
parametrized by $(x, p)$ that captures all the dynamics of the system, meaning that how a system evolves in
time can be calculated once the Hamiltonian is known. In a sense, the Hamiltonian mathematically *represents* 
the system itself, so how transformations of the Hamiltonian can be represented in terms of quantities like
$p$ are important and give a more fundamental representation of what these quantities actually represent. 

Now, to figure out what the quantum generator of translations looks like, we must first define a translation operator, which we do
below:[^translation-operator]

:::{.definition #def-quantum-translation-operator}

# Quantum Translation Operator 
The *translation operator* is a linear operator parametrized by a displacement $a$. On the Hilbert space of
position eigenstates $\ket{x}$, the translation operator $T(a)$ acts as:
$$
	T(a) \ket{x} = \ket{x + a}
$$
:::
Just like in the classical case, let's now Taylor expand $T(a)$ around $a = 0$:
$$
	T(a) = T(0) + a \dv{T}{a}(0) + \dots 
$$
And now, we define an operator $\hat{k}$ such that:
$$
	\hat{k} = i\dv{T}{a}(0) 
$${#eq-khat-definition}
The reason we include the imaginary part $i$ so that $\hat{k}$ can be Hermitian. With this definition of
$\hat{k}$, we can write $T(a)$ as: 
$$
	T(a) = 1 - ia \hat{k} + \dots 
$$
And now, we can see that we've managed to rewrite $T(a)$ purely in terms a Taylor expansion in $\hat{k}$. So,
just like it's classical analogue, we've found an operator $\hat{k}$ from which a general translation $T(a)$
can be built up, and hence we call $\hat{k}$ the generator of translations in quantum mechanics.

So, is $\hat{k}$ then our momentum operator? Not quite! While both $p$ and $\hat{k}$ are their
respective generators of translations, their units are not quite the same. We can see from the Taylor
expansion of $T(a)$ that $\hat{k}$ must have units of inverse length so that $T(a)$ remains dimensionless. On
the contrary, the classical quantity $p$ has units of momentum. So, to fix this discrepancy, we insert a
proportionality constant in front of $\hat{k}$ to make the dimensions work out: 
$$
	\hat{p} = \hbar \hat{k}
$$
and this is the definition of the momentum in quantum mechanics.

<!-- insert some description of the planck constant here, I can't think of anything good to write right now.--> 

### Properties of the Momentum Operator  
Now that we have a proper definition of $\hat{p}$ in $\hat{p} = \hbar \hat{k}$, we return to our original
question: what does $\hat{p}$ do to states $\ket{x}$? This is essentially asking what $\hat{k}$ does to these
states, since $\hat{p}$ is defined in terms of $\hat{k}$ up to a proportionality constant. To start, let's
use the definition of $\hat{k}$ (@eq-khat-definition) and act it on a $\ket{x}$ and see what happens:
$$
	\hat{k}\ket{x} = i\dv{T}{a} \eval{\ket{x}}_{a = 0} = i\dv{a} \eval{\ket{x + a}}_{a = 0} = i \dv{x} \ket{x}
$${#eq-k-on-ket}
The last step may seem strange since we're switching from $\dv{a}$ to $\dv{x}$, but it can be 
motivated using the chain rule:
$$
	i\dv{a} \eval{\ket{x + a}}_{a = 0} = i \dv{x} \dv{x}{a} \eval{\ket{x + a}}_{a = 0}
$$
and $\dv{x}{a}$ is interpreted as the change in $x$ relative to a change in $a$. Since $T(a)$ moves $\ket{x}$
to $\ket{x + a}$, a change in $a$ is equal to a change in $x$, hence $\dv{x}{a} = 1$. Thus, we're left with
the desired result:
$$
	i\dv{a} \eval{\ket{x + a}}_{a = 0} = i \dv{x} \ket{x}
$$
Since we've also just discovered how we can write wavefunctions as $\psi(x) = \braket*{x}{\psi}$, let's also
work what $\hat{k}$ does to those. First, consider a ket $\ket{\psi}$ and its wavefunction $\psi(x) = 
\braket*{x}{\psi}$, and now define $\ket{\phi} = T(a) \ket{\psi}$. Now, we calculate $\phi(x)$, the
wavefunction of $\ket{\phi}$:
$$
	\phi(x) = \braket*{x}{\phi} = \mel{x}{T(a)}{\psi} = \int \mel{x}{T(a)}{x'} \braket*{x'}{\psi} \ dx'
$$
where again, we insert the resolution of the identity. From the definition of $T(a)$ we have 
$T(a) \ket{x'} = \ket{x + a}$ and $\braket*{x'}{\psi} = \psi(x')$, so we have:
$$
	\int \mel{x}{T(a)}{x'} \braket*{x'}{\psi}\ dx' = \int \braket*{x}{x' + a} \psi(x') \ dx' = \int \delta(x
	- x' - a) \psi(x') = \psi(x - a)
$$
With this result, we can now write how $T(a)$ transforms a wavefunction:
$$
	\left( T(a) \psi \right)(x) = \psi(x - a)
$${#eq-translation-on-psi}
Now, we can write down what $\hat{k}$ does with wavefunctions as well:
$$
	(\hat{k} \psi)(x) = i \eval{\left( \dv{T(a)}{a} \psi\right)(x)}_{a = 0} = i \dv{a} \eval{\psi(x - a)}_{a
	= 0} = -i \dv{\psi(x)}{x}
$${#eq-k-on-psi}
where again, we make use of the chain rule to get $\dv{a} = \dv{x} \dv{x}{a} = \dv{x}$. Then, since $\hat{p}
= \hbar \hat{k}$, we now know what $\hat{p}$ does to wavefunctions as well:
$$
	(\hat{p} \psi)(x) = (\hbar \hat{k} \psi)(x) = -i \hbar \dv{\psi(x)}{x}
$$
and this is where we arrive at the famous definition of the momentum operator:
$$
	\hat{p} = -i\hbar \dv{x}
$$
We can also generalize all these notions to three dimensions pretty easily, by replacing scalars with vectors
and derivatives with partial derivatives. Starting with $\hat{k}$, we use $\hat{k}_i$ to denote the $\hat{k}$
vector in the $i$-th direction:
$$
	\hat{k}_i = i \eval{\pdv{T(\mathbf{a})}{a_i}}_{a = 0}
$${#eq-k-on-psi-multidimensional}
@eq-k-on-ket and @eq-k-on-psi also generalize easily:
$$
	\hat{k}_i \ket{\mathbf{x}} = i \pdv{x_i} \ket{\mathbf{x}}, \quad (\hat{k}_i \psi)(\mathbf{x}) = -i
	\pdv{\psi(\mathbf{x})}{x_i}
$$
Finally, since $\hat{p} = \hbar \hat{k}$, we now know what the momentum operator does to $\ket{x}$:
$$
	\hat{p}_i \ket{\mathbf{x}} = i \hbar \pdv{x_i} \ket{\mathbf{x}}, \quad (\hat{p}_i \psi)(\mathbf{x}) = -i \hbar
	\pdv{\psi(\mathbf{x})}{x_i}
$$

### Canonical Commutation Relations
The last property we'll explore about $\hat{k}$ is the commutation relations between $\hat{k}_i$ and
$\hat{k}_j$ and also discuss the relation between $\hat{x}_i$ and $\hat{k}_j$. The commutation $[\hat{k}_i,
\hat{k}_j]$ can be derived using @eq-k-on-psi-multidimensional:  
$$
	\begin{align*}
		\hat{k}_i \hat{k}_j \psi(\mathbf{x}) = 
		\left( -i \pdv{x_i} \right) \cdot \left(-i \pdv{x_j}\right) \psi(\mathbf{x}) = -\pdv[2]{}{x_i}{x_j} \psi(x)
	\end{align*}
$$
From here, we can see that switching the order $\hat{k}_j \hat{k}_i$ flips the order of the mixed partial
derivative, but we know from multivariate calculus that the mixed partial derivatives are equal, 
provided that $\psi(x)$ satisfies some continuity conditions.[^clairaut] For our purposes, we will assume
that $\psi(x)$ is well-behaved enough that this will always be true. Therefore, the order in which $\hat{k}_i$ and $\hat{k}_j$
are arranged does not matter, and therefore the commutation relation is:
$$
	[\hat{k}_i, \hat{k}_j] = 0
$$
Finally, we can also work out the commutator $[\hat{x}_i, \hat{k}_j]$ by applying them in alternating order to a 
wavefunction $\psi(x)$:  
$$
\begin{align*}
	\hat{x}_i \hat{k}_j \psi &= \hat{x_i} \left( -i \pdv{x_j} \right)\psi = -i x_i \pdv{\psi}{x_j}\\
	\hat{k}_j \hat{x}_i \psi &= -i \pdv{x_j} \left( x_i \psi \right) = -i \delta_{ij} \psi - i x_i \pdv{\psi}{x_j}
\end{align*}
$$
Now we put the pieces together:
$$
	(\hat{x}_i \hat{k}_j - \hat{k}_j \hat{x}_i) \psi 
	= -i x_i \pdv{\psi}{x_j} - \left( -i \delta_{ij} \psi - i x_i \pdv{\psi}{x_j} \right) = i \delta_{ij}\psi
$$
and so we get the relation:
$$
	[\hat{x}_i, \hat{k}_j] = i\delta_{ij}
$${#eq-xk-commutation}

And since $\hat{p} = \hbar \hat{k}$, we can now write the famous commutation relation:
$$
	[\hat{x}_i, \hat{p}_j] = i\hbar \delta_{ij}
$$
With this established, we can now use @thm-generalized-uncertainty to to derive the famous Heisenberg
uncertainty principle by using $A = \hat{x}$, $B = \hat{p}$ and taking the square root:
$$
	\Delta \hat{x}_i \Delta \hat{p}_i \geq \frac{\hbar}{2} \delta_{ij}
$${#eq-position-momentum-uncertainty}

Typically in any undergraduate treatment of this material, this result would simply be quoted and accepted
without proof. However, by stepping through the derivation hopefully this result feels more like a natural
consequence of our formalism than a result pulled from thin air.

<!-- write something here pls --> 

<!-- 
This was the first iteration of explaining the momentum operator -- I think it goes into classical
mechanics more than I want to; I'd like to make it shorter which is why I'm rewriting it. Keeping it here in
case we want to bring it back 



So, to begin our derivation, we first turn to classical mechanics for a hint: in Lagrangian and Hamiltonian
mechanics, translational invariance (also sometimes called translational symmetry) directly leads to
the conservation of momentum, which hints at a link between translation and momentum. Motivated by this, we
will begin our derivation by looking closely at the role of $p$ in classical mechanics, and define the
quantum operator $\hat{p}$ in a way that is consistent with the classical $p$.


### The Classical Generator of Translations

:::{.warning}
This section will make use of Lagrangians, Hamiltonians, and Poisson brackets: mathematical objects which appear frequently
(and almost exclusively, with the exception of quantum field theory) in the study of classical mechanics. 
Since this is a quantum mechanics book, we will spare the formal details about these objects, 
and ask that you read our notes on classical mechanics (which are being written) for a more rigorous treatment. 
Here, we'll focus more on what these quantities represent, without delving into the formalism that underpins them.
:::

The particular property of momentum we're going to concern ourselves with is that the momentum 
$p$ acts as the *generator of translations* in classical mechanics. To begin,
the *Lagrangian* is an object which, using a set of generalized
coordinates $\mathbf{x}, \dot{\mathbf{x}}$ (here $\dot{\mathbf{x}}$ represents the velocity vector), 
captures *all* the dynamics of a system, and how a system evolves can be calculated from it.
The *canonical momentum* is a quantity which can be derived from the Lagrangian:
$$
	\mathbf{p} = \pdv{\mathcal{L}}{\dot{\mathbf{x}}}
$$
ordinarily, this would be equal to the *kinetic momentum*, $\mathbf{p} = m \dot{\mathbf{x}}$, which is its
definition in Newtonian mechanics. However, when the Lagrangian has other terms dependent on
$\dot{\mathbf{x}}$, these two quantities differ. To see how the canonical momentum generates these
translations, we first define a translation operator below. 

:::{.definition #def-classical-translation-operator}

# Classical Translation Operator

The classical translation operator $T_{\text{cl}}(a)$ acting on a function $f(x, p)$ is given by:
$$
	(T_{\text{cl}}(a) f)(x, p) = f(x - a, p)
$$
:::
Intuitively, this definition should make sense: a translation operator should only modify the position
variables, while leaving the momentum terms alone. Now, consider a Taylor expansion of $T_{\text{cl}}(a)$
for a small displacement $a$:
$$
	(T_\text{cl}(a) f) (x, p) = f(x - a, p) = f(x, p) - a \pdv{f}{x} + \frac{a^2}{2!}
	\pdv[2]{f}{x} (x, p) + \dots 
$$
it turns out that using Poisson brackets (more on these in @sec-poisson-bracket), one can write this as:
$$
	f(x - a, p) = f(x, \dot x), + a \{p, f\} + \frac{a^2}{2} \left\{ p, \left\{ p, f \right\} \right\} +
	\dots 
$$
So, it's clear from this expression that on a function $f$ parametrized by position and momentum, the
operator $T_\text{cl}(a)$ can be built up in terms of the canonical momentum $p$. The reason this is
significant is becasue there's another quantity    

 


So, it's clear from this expression that the translation operator $T_\text{cl}(a)$ can be written in terms of
an expansion involving the canonical momentum $p$, which is why we call $p$ the *generator of translations*
in classical mechanics. 

:::{.remark}
We have glossed over a *lot* in this chapter, and to be honest 
:::

# Translation Operators 
First, we define the translation operator, which as its name suggests, takes a ket $\ket{x}$ and moves it
space to $\ket{x + a}$:

:::{.definition #def-quantum-translation-operator}

# Quantum Translation Operator 
The *translation operator* is a linear operator parametrized by a displacement $a$. On the Hilbert space of
position eigenstates $\ket{x}$, the translation operator $T(a)$ acts as:
$$
	T(a) \ket{x} = \ket{x + a}
$$
:::
Simple enough. What happens to $T$ when we act it on wavefunctions? Well, following the same logic as the
derivation with the momentum, let's first define a wavefunction $\psi(x) = \braket*{x}{\psi}$, and define a
second wavefunction $\phi(x) = T(a) \ket{\psi} = \braket*{x}{\phi}$. Now, we have:
$$
	\phi(x) = \braket*{x}{\phi} = \mel{x}{T(a)}{\psi} = \int \mel{x}{T(a)}{x'} \braket*{x'}{\psi} \ dx'
$$
where again, we insert the resolution of the identity. Now, from the definition of $T(a)$ we have 
$T(a) \ket{x'} = \ket{x + a}$ and $\braket*{x'}{\psi} = \psi(x')$, so we have:
$$
	\int \mel{x}{T(a)}{x'} \braket*{x'}{\psi}\ dx' = \int \braket*{x}{x' + a} \psi(x') \ dx' = \int \delta(x
	- x' - a) \psi(x') = \psi(x - a)
$$
With this result, we can now write an expression similar to @eq-position-definition:
$$
	\left( T(a) \psi \right)(x) = \psi(x - a)
$${#eq-translation-on-psi}

In other words, what this tells us is that the translation operator $T(a)$ translates the whole function
$\psi(x)$ to the right by $a$ units, as expected. This also generalized cleanly to three dimensions, by
replacing scalars with vectors:
$$
	T(\mathbf{a}) \ket{\mathbf{x}} = \ket{\mathbf{x} + \mathbf{a}}
$$

### Generators of Translations
Above, we defined the translation operator $T(a)$ which displaces $\psi(x)$ by a finite distance $a$, but
one can also imagine $T(a)$ being made up of many infinitesimal translations, and these infinitesimal
versions are called the *generator* of translations. For a small displacement $a$, we we can Taylor expand
$T(a)$ in powers of $a$:
$$
	T(a) = T(0) + a \dv{T}{a}(0) + \dots 
$$
Remember that this is an *operator* expansion, so all the terms on the right are operators as well. In
particular, $T(0)$ is an operator denoting a displacement of zero units, or basically the identity. For
subsequent terms, we define:
$$
	\hat{k} = i\dv{T}{a}(0) 
$$
The reason we include the imaginary part $i$ so that $\hat{k}$ can be Hermitian. With this definition of
$\hat{k}$, we can write $T(a)$ as: 
$$
	T(a) = 1 - ia \hat{k} + \dots 
$$
In the context of translations, $\hat{k}$ is what we call the *generator* of translations, as it defines
infinitesimal translations, which we then use to define larger transformations. Since $\hat{k}$ is also an
operator, we should also work out how it acts on kets and wavefunctions. Starting with kets:
$$
	\hat{k}x = i\dv{T}{a} \eval{\ket{x}}_{a = 0} = i\dv{a} \eval{\ket{x + a}}_{a = 0} = i \dv{x} \ket{x}
$$
The last step may seem strange since we're switching from $\dv{a}$ to $\dv{x}$, but it can be 
motivated using the chain rule:
$$
	i\dv{a} \eval{\ket{x + a}}_{a = 0} = i \dv{x} \dv{x}{a} \eval{\ket{x + a}}_{a = 0}
$$
and $\dv{x}{a}$ is interpreted as the change in $x$ relative to a change in $a$. Since $T(a)$ moves $\ket{x}$
to $\ket{x + a}$, a change in $a$ is equal to a change in $x$, hence $\dv{x}{a} = 1$. Thus, we're left with
the desired result:
$$
	i\dv{a} \eval{\ket{x + a}}_{a = 0} = i \dv{x} \ket{x}
$$
Now that we know how $\hat{k}$ acts on kets, let's figure out how it acts on wavefunctions. We use
@eq-translation-on-psi to help us out:
$$
	(\hat{k} \psi)(x) = i \eval{\left( \dv{T(a)}{a} \psi\right)(x)}_{a = 0} = i \dv{a} \eval{\psi(x - a)}_{a
	= 0} = -i \dv{\psi(x)}{x}
$${#eq-k-on-psi}
where again, we make use of the chain rule to get $\dv{a} = \dv{x} \dv{x}{a} = \dv{x}$. We can also
generalize $\hat{k}$ to three dimensions using $\hat{\mathbf{k}}$ with comopnents $\hat{k}_i$, defined as:
$$
	\hat{k}_i = i \eval{\pdv{T(\mathbf{a})}{a_i}}_{a = 0}
$$
essentially, each $\hat{k}$ encodes the infinitesimal translation independently, which is then
combined into a vector form. 

One can also work out the commutation relations between $\hat{k}_i$ and $\hat{k}_j$, which will be useful
to later derive the commutation relation between $\hat{x}$ and $\hat{p}$. It's easy to see the commutation
relation when we compute $\hat{k}_i \hat{k}_j \ket{x}$ by generalizing @eq-k-on-psi to three dimensions:
$$
	\begin{align*}
		\hat{k}_i \hat{k}_j \psi(\mathbf{x}) = 
		\left( -i \pdv{x_i} \right) \cdot \left(-i \pdv{x_j}\right) \psi(\mathbf{x}) = -\pdv[2]{}{x_i}{x_j} \psi(x)
	\end{align*}
$$
From here, we can see that switching the order $\hat{k}_j \hat{k}_i$ flips the order of the mixed partial
derivative, but we know from multivariate calculus that the mixed partial derivatives are equal, 
provided that $\psi(x)$ satisfies some continuity conditions.[^clairaut] For our purposes, $\psi(x)$ is
well-behaved enough that this will always be true. Therefore, the order in which $\hat{k}_i$ and $\hat{k}_j$
are arranged does not matter, and therefore the commutation relation is:
$$
	[\hat{k}_i, \hat{k}_j] = 0
$$
Finally, we can also work out the commutator $[\hat{x}_i, \hat{k}_j]$ by applying them to a $\psi(x)$ and
seeing what we get:
$$
\begin{align*}
	\hat{x}_i \hat{k}_j \psi &= \hat{x_i} \left( -i \pdv{x_j} \right)\psi = -i x_i \pdv{\psi}{x_j}\\
	\hat{k}_j \hat{x}_i \psi &= -i \pdv{x_j} \left( x_i \psi \right) = -i \delta_{ij} \psi - i x_i \pdv{\psi}{x_j}
\end{align*}
$$
Putting these together
$$
	(\hat{x}_i \hat{k}_j - \hat{k}_j \hat{x}_i) \psi 
	= -i x_i \pdv{\psi}{x_j} - \left( -i \delta_{ij} \psi - i x_i \pdv{\psi}{x_j} \right) = i \delta_{ij}\psi
$$
and so we get the relation:
$$
	[\hat{x}_i, \hat{k}_j] = i\delta_{ij}
$${#eq-xk-commutation}
-->

## The Schrödinger Equation
We are now finally ready to develop the Schrödinger equation, which will serve as the main equation all of
quantum mechanics is aimed to solve to describe physical systems. To do so properly, however, we need to
quantify how to determine a system's energy in a quantum-mechanical system, which will require us to find the
quantum analog of the *Hamiltonian*. We set everything up in a similar manner to how we presented (and
ultimately derived) the momentum.

### Time-Evolution Operator 
At their core, any general equation for a specified field of physics describes how that particular system
evolves in time. Some systems will not change in time, but being able to quantify how certain properties
change as time advances is the core of that particular field. In classical mechanics, we saw that first
through **Newton's Laws of Motion**, which described how forces acting on an object in a system affect said
object. Later on, we quantified how to describe the change in a system's *energy*, for which we used the
**Lagrangian/Hamiltonian Equations of Motion**. In quantum mechanics, we want to something very similar; we wish to understand how to express how a system
evolves in time by quantifying its energy. 

Let's now finally introduce time dependence into our ket vectors. Label the pure state of a system at some
initial time $t_0$ by $\ket{\psi(t_0)}$, and label that same state at a final time $t$ by $\ket{\psi(t)}$.
We now claim the existence of a *time-evolution operator*, which we'll denote $U(t,t_0)$, that transforms the
state $\ket{\psi(t_0)}$ into the state $\ket{\psi(t)}$:
$$
	\ket{\psi(t)} = U(t,t_0)\ket{\psi(t_0)}
$${#eq-time-evolution-def}
Let's properly define this operator:

:::{.definition #def-time-evolution-operator}

# Time-Evolution Operator
The *time-evolution operator*, denoted $U(t,t_0)$, evolves a quantum state from initial time $t_0$ to final
time $t$, while satisfying the following three properties:

1. $U$ should reduce to the identity operator at $t=t_0$: $$
	U(t_0,t_0) = 1
$$
2. $U$ is unitary: $$
	U(t,t_0)^{-1} = U(t,t_0)^{\dagger}
$$
3. $U$ should satisfy the *composition property*: $$
	U(t_2,t_1)U(t_1,t_0) = U(t_2,t_0)
$$
:::

Each of these properties make intuitive sense. Starting with the first, evolving between the same time is
equivalent to not evolving in time at all, meaning the states before and after such a time evolution action
should be equivalent. Secondly, we want to preserve probabilities. In other words, the probability of
something like finding a particle somewhere in space should be $1$ regardless of *when* we measure in time.
Thus, evolving forwards vs. backwards in time shouldn't affect such probabilities. Finally, evolving a state
from an initial time to a second time and then evolving to a final third should naturally produce the same result
as directly evolving from the initial time to the final.

### The Hamiltonian
Let's now consider some infinitesimal time evolution from $t$ to $t+\epsilon$, for some small $\epsilon$. We
can expand $U$ to first order and tack on an additional correction term:
$$
	U(t+\epsilon,t) = 1 - i\epsilon\Omega(t) + \dots
$${#eq-time-evolution-expansion}
Our correction term is defined as follows (with an extra $i$ factor to make the operator Hermitian):
$$
	\Omega(t)  = i\pdv{t'}U(t',t)\bigg|_{t'=t}
$${#eq-generator-time-evolution}
This operator $\Omega(t)$ is then our *generator of time evolution* in quantum mechanics, since it
is precisely the correction term that advances a state in time by small increments. Combining these terms in
large quantities will advance time by larger increments.

In classical mechanics, the Hamiltonian (which we'll henceforth represent with $H$) is fundamentally the
generator of time translations, since it describes how a system evolves in time. Let's consider some
classical observable $f(x,p)$ (a function in position and momentum) that exhibits time dependence due to how
$x$ and $p$ evolve in time. Expanding to first order in $t$ gives:
$$
	f(t+\epsilon) = f(t) + \epsilon\dv{f}{t} = f(t)+\epsilon\left(\dot{x}\pdv{f}{x} + \dot{p}\pdv{f}{p}\right) 
	= f(t) + \epsilon\left(\pdv{H}{p}\pdv{f}{x} - \pdv{H}{x}\pdv{f}{p}\right) = f(t) - \epsilon\{H,f\}
$$
where the last equality again makes use of the Poisson bracket. 

Much like the momentum operator, the quantum analog of the classical Hamiltonian (henceforth denoted
$\hat{H}$) should also be a generator of time evolution. However, we run into the same issue with the units as we did with
the momentum, so we insert a proportionality constant here as well: 
$$
	\hat{H}(t) = \hbar\Omega(t)
$$
We can plug this back into @eq-time-evolution-expansion to express the time evolution operator exclusively in terms
of the Hamiltonian:
$$
	U(t+\epsilon,t) = 1 - \frac{i\epsilon}{\hbar}\hat{H}(t) + \dots
$$

:::{.remark}
Classical Hamiltonians will depend on time in the presence of time-dependent forces or fields. As such, we
will generally expect the quantum Hamiltonian $\hat{H}$ to also be time-dependent. There will still, however,
be special time-independent cases that we will choose to study closely (this may or may not be
foreshadowing).
:::

It is, of course, a nontrivial question whether or not this $\hbar$ constant is the same one that is used in
@sec-momentum-operator. As it turns out, there is a requirement that these $\hbar$'s be equivalent (known as *relativistic
covariance*), but this won't be relevant to us until we discuss relativistic quantum mechanics. To avoid a
lengthy and complicated discussion, we will simply note here that this $\hbar$ constant is the same as the
one that appears in momentum and energy representations. 

### Deriving the Schrödinger Equation
With that established, we now need a differential equation that we can solve to ascertain physical properties
of a system. Classically, that would involve Hamilton's equations of motion (or Newton's or Lagrange's,
depending on the scenario). So, let's find a differential equation for time-evolution operators. Let's start
with the basic definition of the derivative:
$$
	\pdv{U(t,t_0)}{t} = \lim_{\epsilon\to0}\frac{U(t+\epsilon,t_0) - U(t,t_0)}{\epsilon}
$$
The composition property in @def-time-evolution-operator allows us to rewrite $U(t+\epsilon,t_0)$:
$$
	U(t+\epsilon,t_0) = U(t+\epsilon,t)U(t,t_0)
$$
Substituting this back into our definition of the derivative and factoring out $U(t,t_0)$ gives:
$$
	\pdv{U(t,t_0)}{t} = \left(\lim_{\epsilon\to0}\frac{U(t+\epsilon,t) - 1}{\epsilon}\right)U(t,t_0) =
	\pdv{U(t',t)}{t'}\bigg|_{t'=t}U(t,t_0)
$$
By @eq-generator-time-evolution, the RHS derivative can be replaced with $-i\Omega(t)$, which in turn can be
replaced with $\frac{-i\hat{H}(t)}{\hbar}$. Assembling all of that together (and rearranging a few
prefactors) gives us our differential equation for the time evolution operator in terms of the Hamiltonian:
$$
	i\hbar\pdv{U(t,t_0)}{t} = \hat{H}(t)U(t,t_0)
$${#eq-uderiv-hamiltonian}
Now, we can finally get rid of $U$ by differentiating @eq-time-evolution-def with respect to time and substituting
in this new expression to get rid of the time evolution (remember also to tack on the relevant $i\hbar$
prefactor):
$$\begin{align*}
	i\hbar\pdv{t}\ket{\psi(t)} &= i\hbar\pdv{t}\left(U(t,t_0)\ket{\psi(t_0)}\right) =
	i\hbar\left[\pdv{U(t,t_0)}{t}\ket{\psi(t_0)} + \cancelto{0}{U(t,t_0)\pdv{t}\ket{\psi(t_0)}}\right] = \\
	&= i\hbar\pdv{U(t,t_0)}{t}\ket{\psi(t_0)} = \hat{H}(t)U(t,t_0)\ket{\psi(t_0)} = \hat{H}(t)\ket{\psi(t)}
\end{align*}$$
We summarize this as the *Schrödinger equation*:

:::{.theorem #thm-schrodinger}
# Schrödinger Equation
$$
	i\hbar\pdv{t}\ket{\psi(t)} = \hat{H}(t)\ket{\psi(t)}
$$
:::

More precisely, this is the *time-dependent* Schrödinger equation, since we are allowing for a time-dependent
Hamiltonian. This is the most general form of the equation, since it makes no claims as to what form
$\hat{H}$ takes and it doesn't express $\ket{\psi}$ in any particular basis. Can we be a bit more precise
about the Hamiltonian? As a matter of fact, we can!

Classically, the Hamiltonian of a system is given as the sum of its kinetic and potential
energies[^natural-coordinates] (ie, the total energy of the system):
$$
	H = T + V
$$
Here, $T$ represents the kinetic energy, while $V$ represents the potential energy. The kinetic energy is
given by $\frac{p^2}{2m}$, and the potential energy is generally unknown and will be system-depedent.
Translating all respective quantities to quantum operators gives us the quantum Hamiltonian:
$$
	\hat{H} = \frac{\hat{p}^2}{2m} + \hat{V}
$$
Translating this into configuration space wavefunction notation gives us:
$$
	\hat{H} = -\frac{\hbar^2}{2m}\pdv[2]{x} + V(x,t)
$${#eq-hamiltonian-wavefunction-form}
Generally, the potential will be time-dependent. Substituting all of that in gives us a slightly more
specific form of the Schrödinger equation that we will actually apply to solve problems:

:::{.theorem #thm-tdse}
# Time-Dependent Schrödinger Equation
$$
	\left(\frac{\hbar^2}{2m}\pdv[2]{x} + V(x,t)\right)\psi(x,t) = i\hbar\pdv{\psi(x,t)}{t}
$$
:::

To be a bit more precise, this was the one-dimensional form of the Schrödinger equation. In three dimensions,
we replace the derivatives with Laplacians:
$$\left(-\frac{\hbar^2}{2m}\nabla^2 + V(\mathbf{x},t)\right)\psi(\mathbf{x},t) =
i\hbar\pdv{\psi(\mathbf{x},t)}{t}$$
This is only one representation of the Schrödinger equation in functional form. There are, of course, many
other bases in which we can represent (and subsequently solve) this equation. The most natural alternat form
is writing the Schrödinger equation in momentum space, which we can do with a simple Fourier transform. 

### Time-Independent Schrödinger Equation
While wavefunctions, potentials, and Hamiltonians will generally admit time dependence, it is also worth
analyzing some time-independent potentials as a special case and a useful model for certain problems in
nonrelativistic quantum mechanics. As such, we can write a time-independent version of the Schrödinger
equation, where we instead focus on finding the energy eigenstates (or *stationary states*, since they don't
evolve in time). Thus, we can represent the Schrödinger equation as an eigenvalue problem:

:::{.theorem #thm-tise}

# Time-Independent Schrödinger Equation
$$
	\hat{H}\ket{\psi} = E\ket{\psi}
$$
:::

Alternatively, you can enumerate the eigenstates $\ket{n}$ and the associated energy eigenvalues $E_n$:
$$
	\hat{H}\ket{n} = E_n\ket{n}
$$
Crucially, $n$ can represent one or more quantum numbers required to specify the energy eigenstate.

:::{.remark}
This will become much more relevant in higher dimensions, where we will have radial and angular components,
etc.
:::

For the time being, much of our work will involve solving the time-independent Schrödinger equation for
various relatively simple time-independent potentials. Should we choose to reintroduce time dependence, we
will be able to do so with a separate expression that stores all of the information on the system's time
dependence (this is explored in more detail in the next chapter).

## Pictures in Quantum Mechanics
As it turns out, there are multiple different interpretations for how operators and wavefunctions behave. So
far, we have been operating in only one of these so-called pictures, but it is useful to quantify the
difference between the two of them and see how each may be more applicable depending on the type of problem
we are trying to solve.


### Schrödinger Picture
So far, we have been operating under the assumption that the *wavefunctions* are what evolve in time, with
observables remaining fixed. In other words, the way we measure position will never depend on what point in
time we choose to measure that position. This is what's known as the *Schrödinger picture*.

Since our wavefunction is what describes the state of the system, it is natural for it to be the quantity
that evolves in time. As a consequence, most problems we will tackle and most attempts at solving the
Schrödinger equation will be undertaken in the Schrödinger picture.

:::{.notation}
In this section, we denote operators and kets in the Schrödinger picture with a subscripted
$S$:
$$
	\ket{\psi} \to \ket{\psi_S(t)}, \quad \hat{A} \to \hat{A}_S
$$
In general, if a subscript is not present, then we assume that we are working in the Schrödinger picture.
:::

### Heisenberg Picture
That being said, there is another way we can interpret systems. What if, instead of letting the wavefunction
evolve in time whilst keeping observables static, we go the other way: let *observables* evolve in time
whilst keeping wavefunctions static. This is what's known as the *Heisenberg picture*, with our equations of
motion now involving time-derivatives of operators rather than wavefunctions.

:::{.notation}
We denote operators and kets in the Heisenberg picture with a subscripted
$H$:
$$
	\ket{\psi} \to \ket{\psi_H}, \quad \hat{A} \to \hat{A}_H(t)
$$
:::

Since we are eliminating time dependence from kets in the Heisenberg picture, we relate them to the
corresponding time-dependent state vector in the Schrödinger picture by a time evolution:
$$
	\ket{\psi_H} = U(t,t_0)^{\dagger}\ket{\psi_S(t)}
$$
This is equivalent to writing that the Heisenberg state vector is simply the Schrödinger state vector at
the initial time $t_0$:
$$
	\boxed{\ket{\psi_H} =
	\ket{\psi_S(t_0)}}
$${#eq-schrodinger-heisenberg-ket}

Now, operators in the Schrödinger picture are still generally allowed to have an explicit time
dependence, we need to introduce a separate (implicit) time depedence when relating to the
Heisenberg operator:
$$
	\hat{A}_H(t) = U(t,t_0)^{\dagger}\hat{A}_S(t)U(t,t_0)
$${#eq-schrodinger-heiseberg-operator}
Since the Heisenberg kets don't have any time dependence, we no longer have a time evolution equation
for them like we did in the Schrödinger picture. Instead, we need a time evolution equation for Heisenberg
operators. If we differentiate the above equation and once again invoke @eq-uderiv-hamiltonian, we get:
$$
	i\hbar\dv{\hat{A}_H}{t} = -U^{\dagger}(t,t_0)\hat{A}_SU(t,t_0) + U^{\dagger}(t,t_0)\hat{A}_S\hat{H}U(t,t_0) 
	+ i\hbar U^{\dagger}(t,t_0)\pdv{\hat{A}_S}{t}U(t,t_0)
$$
Notice, however, that the first two terms on the RHS can be converted to their Heisenberg
equivalents by @eq-schrodinger-heiseberg-operator:
$$
	-U^{\dagger}(t,t_0)\hat{H}\hat{A}_SU(t,t_0) + U^{\dagger}(t,t_0)\hat{A}_S\hat{H}U(t,t_0) 
	= -\hat{H}_H\hat{A}_H + \hat{A}_H\hat{H}_H = [\hat{A}_H,\hat{H}_H]
$$
The final term on the RHS can be rewritten in a similar manner to represent the derivative of the operator
$\hat{A}$ in the Heisenberg picture:
$$
	i\hbar U^{\dagger}(t,t_0)\pdv{\hat{A}_S}{t}U(t,t_0) = i\hbar\left(\pdv{\hat{A}}{t}\right)_H
$$
Putting these together gives us the *Heisenberg equations of motion*:

:::{.theorem #thm-heisenberg-eoms}
# Heisenberg Equations of Motion 
$$
	i\hbar\dv{\hat{A}_H}{t} = [\hat{A}_H,\hat{H}_H] + i\hbar\left(\pdv{\hat{A}}{t}\right)_H
$$
:::

If the prefactors are annoying, we can instead write it as:
$$
	\dv{\hat{A}_H}{t} = -\tfrac{i}{\hbar}[\hat{A}_H,\hat{H}_H] + \left(\pdv{\hat{A}}{t}\right)_H
$$
Whenever we operate in the Heisenberg picture, @thm-heisenberg-eoms will be the equation(s) we will be
interested in solving rather than anything to do with kets.

### Equivalence of the Pictures
Despite the fact that these two pictures seem fundamentally different and involve letting two completely
different types of objects hold time dependence, they actually turn out to be equivalent. This makes sense,
because the solution to a particular problem shouldn't depend on the method used to solve that problem.
Instead of merely saying that, however, let's take the time now to prove that algebraic relations are
equivalent between the two pictures. 

In the previous section, we saw how to convert kets and operators between the Schrödinger and Heisenberg pictures, but what about 
algebraic relations between operators/kets? Let's consider some Schrödinger operator $\hat{A}_S$, related to the Heisenberg 
operator $\hat{A}_H$ by the usual $\hat{A}_H = U^{\dagger}\hat{A}_SU$ (here, $U=U(t,t_0)$, where we dropped the functional 
notation for brevity). Now suppose we have a different Schrödinger operator $\hat{B}_S = f(\hat{A}_S)$, where $f$ is some 
function. Let's see what $\hat{B}_H$ would look like:
$$
	\hat{B}_H = U^{\dagger}f(\hat{A}_S)U = f(U^{\dagger}\hat{A}_SU) = f(\hat{A}_H)
$$
<!-- TODO: write up definition of function of an observable in formalism chapter -->
Wait, hold on a second; why can we just pull the $U$'s into the function? We can start by convincing
ourselves that this true for simple forms of $f$, such as a polynomial or power series. Take, for
instance, $f(\hat{A}_S) = \hat{A}^2_S$:
$$
	\hat{B}_H = U^{\dagger}\hat{A}_S\hat{A}_SU =
	U^{\dagger}\hat{A}_SUU^{\dagger}\hat{A}_SU = \hat{A}_H\hat{A}_H = \hat{A}_H^2
$$
More generally, we can prove this result holds by recalling the definition of the function of an
observable discussed in the Formalism chapter. We won't go into too much detail here, so we conclude our
discussion with that.

This relation equivalence also holds for products of operators that don't necessarily commute. Suppose we
had $\hat{C}_S = \hat{A}_S\hat{B}_S$, where the latter two don't necessarily commute. Then:
$$
	\hat{C}_H = U^{\dagger}\hat{A}_S\hat{B}_SU =
	U^{\dagger}\hat{A}_SUU^{\dagger}\hat{B}_SU = \hat{A}_H\hat{B}_H
$$
Notably, we can combine the above two results to conclude that commutation relations also maintain the same form across both pictures:
<!-- do we want to show this explicitly or leave as is? -->
$$
	\hat{C}_S = [\hat{A}_S,\hat{B}_S] \implies \hat{C}_H = [\hat{A}_H,\hat{B}_H]
$$
Finally, potentials also have the same form across both pictures:
$$
	U^{\dagger}V(\mathbf{x}_S)U = V(\mathbf{x}_H)
$$
Putting all of these together, we can conclude that the Hamiltonian itself has the same form in both
pictures:
$$
	\hat{H}_S = \frac{\mathbf{p}_S^2}{2m} + V(\mathbf{x}_S) \implies \hat{H}_H = \frac{\mathbf{p}_S^2}{2m} +
	V(\mathbf{x}_H)
$$
We have shown that algebraic relations are the same, but how do we show that the Heisenberg and Schrödinger
pictures are physically equivalent? Well, we need to consider measurable quantities in quantum
mechanics and see how they compare to each other across the two pictures. Each measurable quantity can
be represented in terms of matrix elements of the form $\mel{\phi}{\hat{A}}{\psi}$. Thus, if we
can show that these are equivalent between the two pictures, we can conclude that either picture should
predict (and subsequently yield) the same experimental outcomes. Let's start in the Heisenberg picture:
$$\begin{align*}
	\mel{\phi_H}{\hat{A}_H(t)}{\psi_H} &=
	(\bra{\phi_S(t_0)})(U^{\dagger}(t,t_0)\hat{A}_SU(t,t_0))(\ket{\psi_S(t)}) = \\
	&= (\bra{\phi_S(t_0)}U^{\dagger}(t,t_0))\hat{A}_S(U(t,t_0)\ket{\psi_S(t)}) = \\
	&= \mel{\phi_S(t)}{\hat{A}_S}{\psi_S(t)}
\end{align*}$$
Thus, matrix elements are equivalent between the two pictures, meaning any measurable quantity will be
equivalent between these pictures as well. This means that we can predict the outcome of any experiment
equally well by finding the time evolution of operators in the Heisenbeg picture of the time evolution
of state vectors in the Schrödinger picture.

As is par for the course, it is worth considering a special case. In particular, when the Schrödinger
Hamiltonian $\hat{H}_S$ is time-independent, the time-evolution operator will be a function of $H$ and
thus commute with it. This then means that the Schrödinger and Heisenberg Hamiltonians will be equal:
$$
	\hat{H}_H = U^{\dagger}\hat{H}_SU = U^{\dagger}U\hat{H}_S = \hat{H}_S
$$

### Other Pictures?
Are there other pictures beyond the two that we've considered just now? Yes! In particular, when we start
dealing with something called *time-dependent perturbation theory* (in Part II), we will consider the
*interaction picture*, which can be considered a sort-of intermediary between these two[^interaction-picture]. 
Until then however, we will deal almost exclusively with the Schrödinger picture, where operators are fixed
and states evolve in time. This is, in part, due to the fact that it's somewhat more natural to think about
observable as invariant, and having the state evolve in time instead.


## Probability Current 
<!-- i am far too lazy to write this up as well; can you also take this pls (use griffiths and/or littlejohn) -->

Recall that in our formalism chapter, given a wavefunction $\psi(\mathbf{x}, t)$ in position space, the norm-squared
$|\psi(x, t)|^2$ gives the *probability density* of a position measurement. While the state is allowed to
evolve in time according to the Schrodinger equation, its probability density should still integrate to one.
This is to say that the probability that the particle is measured to be anywhere should always be guaranteed.
To define this notion rigorously, we define the probability density to be the norm-squared of $\psi$:

:::{.definition #def-probability-density}

# Probability Density
Given a wavefunction $\psi(\mathbf{x}, t)$ the probability density is defined as:
$$
	\rho(\mathbf{x}, t) = |\psi(\mathbf{x}, t)|^2
$$
:::

Then, the integral over all space of $\rho(\mathbf{x}, t)$ should always be one:
$$
	\int  \rho(\mathbf{x}, t) \ d^3 \mathbf{x} = \int |\psi(\mathbf{x}, t)|^2 \ d^3 \mathbf{x} = 1
$$
Now, while the integral over all space must be constant, $\rho(\mathbf{x}, t)$ can still evolve in time --
the probability density can flow from one location to another, so long as the total integral remains
constant. Therefore, the probability density obeys a *continuity equation*:

:::{.theorem #thm-conitnuity-equation} 

# Probability Current
$$
	\nabla \cdot \mathbf{J} + \pdv{\rho}{t} = 0
$$
:::
This is the same equation for the conservation of charge in electrodynamics. We interpret this equation to
mean that the "flow" of probability (in time) represented by $\nabla \cdot \mathbf{J}$ should be exactly equal in
magnitude to the change of charge $\pdv{\rho}{t}$. Truthfully, we won't be encountering $\mathbf{J}$ 
very often, but what it represents is still very meaningful, as any description of how a state evolves in
time should. Now, let's derive the explicit form of $\mathbf{J}$ using this definition: 
<!-- I literally can't come up with a good use case for the probabilty current, if you have any better ideas
pls edit. -->   
$$
	\begin{align*}
		\nabla \cdot \mathbf{J} &=  -\pdv{\rho}{t} \\ 
		&= -\pdv{t} \left( \psi^{*} \psi \right) \\ 
		&= -\psi \pdv{\psi^{*}}{t} - \psi^{*} \pdv{\psi}{t}	
	\end{align*}
$$
Now, we use the Schrodinger equation (@thm-schrodinger) to help us expand further:
$$
	\begin{align*}
		\nabla \cdot \mathbf{J} = -\psi\pdv{\psi^{*}}{t} - \psi^{*}\pdv{\psi}{t} &= \psi \frac{i\hbar}{2m} \left( \nabla^2 + V
		\right)\psi^{*} - \psi^{*} \frac{i\hbar}{2m} \left( \nabla^2 + V \right)\psi \\ 
		&= \frac{i\hbar}{2m} \psi \nabla^2 \psi^{*} + \psi V \psi^{*} - \frac{i\hbar}{2m} \psi^{*}
		\nabla^2 \psi - \psi^{*} V \psi \\ 
		&= \frac{i\hbar}{2m}\left( \psi \nabla^2 \psi^{*} - \psi^{*} \nabla^2 \psi \right) 
	\end{align*}
$${#eq-prob-current-derivation}
Now, if we define:

:::{.definition #def-probability-current}

# Probability Current
$$
	\mathbf{J} = \frac{i\hbar}{2m} \left( \psi \nabla \psi^{*} - \psi^{*} \nabla \psi \right)
$$
:::

then $\nabla \cdot \mathbf{J}$ is exactly the final equation in @eq-prob-current-derivation. In particular,
the terms with derivatives on both $\psi$ and $\psi^{*}$ will cancel out, leaving only terms with second
partial derivatives, as desired.


## Commutators
Lastly, even commutators can be derived from classical quantities! Previously, we introduced the notion of
commutators as a way to quantify how close/far two operators are from commuting with each other. However, it
is actually possible to connect this notion to classical mechanics.

### Poisson Brackets {#sec-poisson-bracket}
First, we will introduce the *Poisson bracket*, used extensively in classical mechanics (particularly with
Hamiltonian mechanics):

:::{.definition #def-poisson-bracket}
# Poisson Bracket
The *Poisson bracket* of two functions $f(p_i,q_i,t)$ and $g(p_i,q_i,t)$, denoted $\{f,g\}$, is given as:
$$
	\{f,g\} = \sum_{i}\left(\pdv{f}{q_i}\pdv{g}{p_i} - \pdv{f}{p_i}\pdv{g}{q_i}\right)
$$
:::

Here, $p_i$ represent components of the *generalized momentum*, $q_i$ represent *generalized
coordinates*, and $t$ is time. Together, the make up *canonical coordinates*. We will not worry about
what these mean exactly and save detailed discussion for a book on clasical mechanics. 

The main thing we will note is that we can express the total time derivative of a classical observable
$A(p_i,q_i,t)$ as a sum of the explicit time dependence and implicit time dependence resulting from the time
dependence of $p$ and $q$ using the Poisson bracket:
$$
	\dv{A}{t} = \underbrace{\pdv{A}{t}}_{\text{explicit}} + \underbrace{\{A,H\}}_{\text{implicit}}
$$
This looks suspiciously similar to @thm-heisenberg-eoms, and we can in fact create an explicit mapping
between the Poisson bracket and the commutator to make this work:
$$
	[A,B] \to i\hbar\{A,B\}
$$
We applaud Paul Dirac for noticing this correspondence.

:::{.warning}
There is one important caveat: this isn't an exact correspondence in every scenario, since the commutator is
still defined slightly differently. Fortunately for us, the correspondence will be exact in the most
crucial scenarios. For instance, the Poisson bracket relations for the classical
angular momentum $\mathbf{L}=\mathbf{x}\times\mathbf{p}$ is given by:
$$
	\{L_i,L_j\} = \epsilon_{ijk}L_k
$$[^levi-civita]
Likewise, as we will discover later, the quantum-mechanical commutation relations for the angular
momentum become:
$$
	[\hat{L}_i,\hat{L}_j] = i\hbar\epsilon_{ijk}\hat{L}_k
$$
In other cases, however, the correspondence will only be an approximation.
:::

### Ehrenfest's Theorem
The last thing we'll do in this chapter is compute the time derivative of the expectation value of an
observable. Armed with the Heisenberg equations of motion and an understanding of how to take time
derivatives of operators, let's consider some arbitrary observable $A$:
$$
	\dv{t}\expval{A} = \pdv{t}\braket{\psi}{\hat{A}\psi} = \braket{\pdv{\psi}{t}}{\hat{A}\psi} +
	\braket{\psi}{\pdv{\hat{A}}{t}\psi} + \braket{\psi}{\hat{A}\pdv{\psi}{t}}
$$
Now, the Schrödinger equation tells us that we can replace $i\hbar\pdv{t}\ket{\psi} = \hat{H}\ket{\psi}$.
Substituting that in gives us:
$$
	\dv{t}\expval{A} = -\tfrac{i}{\hbar}\braket{\hat{H}\psi}{\hat{A}\psi} +
	\tfrac{1}{i\hbar}\braket{\psi}{\hat{A}\hat{H}\psi} + \expval{\pdv{\hat{A}}{t}}
$$
Finally, since $\hat{H}$ is Hermitian, we can move it through the inner product and we have that
$\braket{\hat{H}\psi}{\hat{A}\psi} = \braket{\psi}{\hat{H}\hat{A}\psi}$. Combining the first two terms on the
RHS into a commutator, we summarize the final form of our
equation as the *generalized Ehrenfest theorem*:

:::{.theorem #thm-generalized-ehrenfest}
# Generalized Ehrenfest's Theorem
$$
	\dv{t}\expval{A} =\tfrac{i}{\hbar}\expval{[\hat{H},\hat{A}]} + \expval{\pdv{\hat{A}}{t}}
$$
:::

The term "generalized Ehrenfest theorem" to describe the above equation was coined in @griffiths2018, as it
doesn't actually have an official name. Since, however, it is a useful expression that can be used to derive
more specific relations that *are* named, we'll use this term.

Let's put this theorem to the test with two special cases, notably the position and momentum operators.

In this case, let's work out the Heisenberg equations of motion for $x$ and $p$. Plugging them directly into
@thm-heisenberg-eoms gives:
$$
	\dv{t}\mathbf{x}_H = -\tfrac{i}{\hbar}[\hat{\mathbf{x}}_H,\hat{H}_H], \quad 
	\dv{t}\mathbf{p}_H = -\tfrac{i}{\hbar}[\hat{\mathbf{p}}_H,\hat{H}_H]
$$
Since the position and momentum operators don't have explicit time dependence, the final term drops out for
both of them. Now, we can evaluate the commutators: <!--maybe put the derivation here? if not i think it's ok
-->
$$
	\dv{t}\mathbf{x}_H = \frac{\mathbf{p}_H}{m}, \quad \dv{t}\mathbf{p}_H = -\nabla V(\mathbf{x},t)
$$
Taking the expectation value with respect to some $\ket{\psi}$ gives us two special cases of
@thm-generalized-ehrenfest which are collectively named *Ehrenfest's theorem*:

:::{.theorem #thm-ehrenfest}
# Ehrenfest's Theorem 
$$
	\dv{t}\expval{\mathbf{x}} = \frac{\expval{\mathbf{p}}}{m}, 
	\quad \dv{t}\expval{\mathbf{p}} = -\expval{\nabla V(\mathbf{x},t)}$$
:::

If we so desire, we could eliminate $\expval{\mathbf{p}}$ and express the latter relation purely in terms of
$\expval{\mathbf{x}}$:
$$
	m\dv[2]{\expval{\mathbf{x}}}{t} = -\expval{\nabla V(\mathbf{x},t)}
$$

## Conclusion
As mentioned earlier, much of what appears in this chapter is generally omitted in a first course on quantum mechanics 
in favor of jumping straight into the physics and trying to describe systems with new equations. 
Perhaps this may have been easier, but at the end of the day, it is entirely about the journey rather than 
the destination. Since we are not beholden to any schedule and are attempting to organize these notes in 
a way that we felt works best, we have chosen to take the road less traveled. 
There is a light at the end of this tunnel, however; we are at last done with the difficult setup. 
The following chapters will take a much lighter approach that may be more akin to an undergraduate perspective, 
albeit with some formalism sprinkled in every now and then.

Let’s use our newly-acquired tools to finally start describing some basic one-dimensional systems!

[^natural-coordinates]: Those who have studied classical mechanics will recognize that this isn't exactly
true generally: the Hamiltonian only describes the total energy of the system when we are working in a
*natural* coordinate system (ie, the relation between the positional descriptions of particles in a system
and the generalized coordinates is time-independent). In functionally all of our cases, though, we will
simply choose natural coordinate systems, meaning we can safely take the Hamiltonian to represent the total
energy. See [@taylor2005] for a more in-depth description of generalized coordinates and how they affect the
form of the Lagrangian and Hamiltonian.

[^interaction-picture]: Specifically, the time dependence due to some unperturbed base Hamiltonian
$\hat{H}_0$ will be moved from the kets to the operators, while the time dependence due to some perturbation
$\hat{H}_1$ will remain on the kets. 

[^levi-civita]: $\epsilon_{ijk}$ is what's known as the *Levi-Civita tensor* (or symbol). It is yet another
tool used in index notation to compactify notation. We discuss this symbol (and how to effectively utilize
it) in more detail in our appendices.

[^clairaut]: Formally, this is known as *Clairaut's Theorem*, which states that partial derivatives commute
	at a point $p$ if the second partial derivatives of $f$ are continuous around a neighborhood of $p$. 

[^translation-operator]: Formally, one could also define a *classical* translation operator $T_\text{cl}(a)
	f(x, p) = f(x - a, p)$, but inserting this definition would only complicate things, so we've
	decided to omit it. In the quantum picture however, since our formalism *is* founded upon the use of
	operators, we must define a translation operator.
